### ISSUE TITLE
CRCs

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#123]
While developing AXL we noticed a bug when dealing with CRCs. We think it's more correct to use a `uLong` rather than a `uLong*` for storing CRCs. SCR will have to clean this up eventually.

Here is where uLongs are found in SCR: https://github.com/LLNL/scr/search?utf8=✓&q=uLong*&type=

**Comment by adammoody** [comment]
I can take a look.  Do you have a pointer to the bug?

**Comment by becker33** [comment]
It appears this bug is not present in SCR, both from behavior and code inspection.
