### ISSUE TITLE
SCR Fails on Multinode MPI

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#124]
🔥 😢 

There is a fatal MPI error in setting up the redundancy groups. Both on Quartz and new Sierra machines running with 2 tasks / node and 2 nodes.

**Comment by gonsie** [comment]
The parallel file system cannot be a cache target. Perhaps this could be detected with GROUP=WORLD? This could make the config file more clear... or less.

**Comment by becker33** [comment]
@gonsie this must be relatively new, I was using the PFS as a cache target during DataWarp development about a year ago.

**Comment by adammoody** [comment]
@gonsie , do you know if this is still a problem?

**Comment by adammoody** [comment]
I think 2 tasks/node on 2 nodes should be working.  If not, we can reopen.
