### ISSUE TITLE
Route File outside of Start/Complete

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#125]
The route file call often needs to be buried deep within the code base. While a high level knows that this an output phase, the low-level file writer is the one that actually constructs the file name.

It would simplify integration if there were an easy way for the low-level to know if it is an SCR phase. There are two ways I can think of:

1. Expose the SCR State information and allow the users to query that directly.
2. Have SCR detect if the state is idle and, if so, return the original file name (essentially a no-op).

Phrased another way, should this code exist on the user side or on SCR's side?
```C
// in user space
if (SCR_STATE != SCR_STATE_IDLE) {
    SCR_Route_file(orig_name, new_name);
} else {
   new_name = orig_name;
}

// inside SCR_Route_file
if (SCR_STATE == SCR_STATE_IDLE) {
    return orig_name;
}
```

**Comment by gonsie** [comment]
This issue is tied up with 2 others:

### mkdir issue

The current guidance is that codes should remove all mkdir calls when using SCR (by wrapping mkdirs in HAVE_SCR ifndefs). BUT, we now run in to the case where a mkdir may not be called when it really should be (dumping data outside of a SCR Start/Complete pair).

### no-op issue

We have had several requests for the SCR no-op mode. In this mode, SCR essentially does nothing but write the files directly to the PFS (or wherever the app wants).

**Comment by gonsie** [comment]
What if we did add an `SCR_Make_dir` API call?

### Parameters

We would need to take some parameters:

- `-p` make intermediate directories
- `-m` mode
- `clean` option which would delete an existing directory of the same name and create it again (as empty). This is needed for **APPX**.
- `tmp` option where a unique, "temporary" name is chosen by SCR.

### Collective

The question then becomes, should this be a collective call? What about the case where each rank needs to create a unique directory. There is no precedent for collective mkdir however it seems that SCR should be pushing the Apps in this direction.

We could even ship it as feature: SCR does the smart thing so that the application doesn't need to wrap it in `if(rank==0)` check.

As a bonus, implementing an SCR mkdir would allow us to detect if the application is creating one dir per rank (and thus may have filename collisions). SCR could then create this directory hierarchy in the cache.

**Comment by gonsie** [comment]
By not exposing the SCR_State to the application I think we move closer to solving the no-op issue. SCR_Route_file returns the original filename when the state is idle. When combined with SCR_Make_dir, SCR would have the power to create needed directories on the PFS in this no-op case.

**Comment by adammoody** [comment]
This sounds good to get us started.

If collective, what if a process has nothing to contribute?
- take a communicator argument and only procs with valid directories participate
- allow a process to specify NULL if it has nothing to contribute (I think I prefer this option)

- do we allow a process to specify more than one directory per call?

- if an app assigns permissions in SCR_Mkdir, they'll expect those same permissions to be set when we flush the dataset to the file system, so we'll need to track the permissions and set them during our flush and scavenge steps

Once we add SCR_Mkdir, it will likely generate more requests down the line that will probably require us to change the interface or add more calls, so we'll have to be willing to be flexible with this while we converge on its semantics.

**Comment by gonsie** [comment]
Route file outside of a start/complete loop discussion:
- return a non-terminating error code
- return original string
- for high-level debugging print a message

**Comment by adammoody** [comment]
I'll close this out since the immediate issue is resolved.  SCR_Mkdir is worthy of its own issue for tracking, so we'll open up a separate for that.
