### ISSUE TITLE
Uncoordinated Checkpoints

### ISSUE THREAD

**Issue by bethven** [LLNL/scr#129]
Hi,
I would like to know if with LLNL/scr you can run Uncoordinated Checkpoints with MPI applications.
I need to do this and I do not know with what I can do it.
Thank you very much.

**Comment by adammoody** [comment]
Hello, @bethven.  Unfortunately, SCR cannot be used for uncoordinated checkpointing.  SCR only supports global synchronous checkpointing.

There is a lot of research on uncoordinated checkpoints, but I'm less familiar with existing libraries that you can use this.  You will often want to combine it with message logging / replay.

**Comment by adammoody** [comment]
There are libraries for global synchronous, system-level checkpoints.  If that's helpful, look at DMTCP (http://dmtcp.sourceforge.net) or BLCR (http://crd.lbl.gov/departments/computer-science/CLaSS/research/BLCR/).

**Comment by bethven** [comment]
Thak you very much!!!

**Comment by adammoody** [comment]
You're welcome.
