### ISSUE TITLE
undefined reference to `MPI::Comm::Comm()' error with both cmake and spack

### ISSUE THREAD

**Issue by Mosseridan** [LLNL/scr#130]
Hello.
I am getting MPI errors when trying to compile scm with both spack and cmake.
Here is the the cmake output:
` cmake -DWITH_PDSH_PREFIX=/home/idanmos/scr/pdsh_ins -DWITH_DTCMP_PREFIX=/home/idanmos/scr/dtcmp_ins -DCMAKE_INSTALL_PREFIX=../scr_ins ../scr
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The Fortran compiler identification is GNU
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found MPI_C: /usr/lib64/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib64/openmpi/lib/libmpi_cxx.so;/usr/lib64/openmpi/lib/libmpi.so  
-- Found MPI_Fortran: /usr/lib64/openmpi/lib/libmpi_usempi.so;/usr/lib64/openmpi/lib/libmpi_mpifh.so;/usr/lib64/openmpi/lib/libmpi.so  
-- MPI C Compile Flags:  
-- MPI C Include Path:   /usr/include/openmpi-x86_64
-- MPI C Link Flags:      -Wl,-rpath  -Wl,/usr/lib64/openmpi/lib  -Wl,--enable-new-dtags
-- MPI C Libraries:      /usr/lib64/openmpi/lib/libmpi.so
-- MPI CXX Compile Flags: 
-- MPI CXX Include Path:  /usr/include/openmpi-x86_64
-- MPI CXX Link Flags:     -Wl,-rpath  -Wl,/usr/lib64/openmpi/lib  -Wl,--enable-new-dtags
-- MPI CXX Libraries:     /usr/lib64/openmpi/lib/libmpi_cxx.so;/usr/lib64/openmpi/lib/libmpi.so
-- MPI Executable:       /usr/lib64/openmpi/bin/mpiexec
-- MPI Num Proc Flag:    -np
-- Using MPI Fortran header: mpif.h
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Found PDSH: /home/idanmos/scr/pdsh_ins/bin/pdsh  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/idanmos/scr/scr_bld
[idanmos@Printer scr_bld]$ make
Scanning dependencies of target scr_o
[  1%] Building C object src/CMakeFiles/scr_o.dir/scr.c.o
/home/idanmos/scr/scr/src/scr.c: In function ‘scr_start_output’:
/home/idanmos/scr/scr/src/scr.c:966:24: warning: initialization discards ‘const’ qualifier from pointer target type [enabled by default]
   char* dataset_name = name;
                        ^
[  2%] Building C object src/CMakeFiles/scr_o.dir/scr_cache.c.o
[  3%] Building C object src/CMakeFiles/scr_o.dir/scr_cache_rebuild.c.o
[  5%] Building C object src/CMakeFiles/scr_o.dir/scr_compress.c.o
[  6%] Building C object src/CMakeFiles/scr_o.dir/scr_config.c.o
[  7%] Building C object src/CMakeFiles/scr_o.dir/scr_config_mpi.c.o
[  8%] Building C object src/CMakeFiles/scr_o.dir/scr_dataset.c.o
[ 10%] Building C object src/CMakeFiles/scr_o.dir/scr_env.c.o
[ 11%] Building C object src/CMakeFiles/scr_o.dir/scr_err_mpi.c.o
[ 12%] Building C object src/CMakeFiles/scr_o.dir/scr_fetch.c.o
[ 13%] Building C object src/CMakeFiles/scr_o.dir/scr_filemap.c.o
[ 15%] Building C object src/CMakeFiles/scr_o.dir/scr_flush.c.o
[ 16%] Building C object src/CMakeFiles/scr_o.dir/scr_flush_file_mpi.c.o
[ 17%] Building C object src/CMakeFiles/scr_o.dir/scr_flush_sync.c.o
[ 18%] Building C object src/CMakeFiles/scr_o.dir/scr_globals.c.o
[ 20%] Building C object src/CMakeFiles/scr_o.dir/scr_groupdesc.c.o
[ 21%] Building C object src/CMakeFiles/scr_o.dir/scr_halt.c.o
[ 22%] Building C object src/CMakeFiles/scr_o.dir/scr_hash.c.o
[ 23%] Building C object src/CMakeFiles/scr_o.dir/scr_hash_mpi.c.o
[ 25%] Building C object src/CMakeFiles/scr_o.dir/scr_hash_util.c.o
[ 26%] Building C object src/CMakeFiles/scr_o.dir/scr_index_api.c.o
[ 27%] Building C object src/CMakeFiles/scr_o.dir/scr_io.c.o
[ 28%] Building C object src/CMakeFiles/scr_o.dir/scr_log.c.o
[ 30%] Building C object src/CMakeFiles/scr_o.dir/scr_meta.c.o
[ 31%] Building C object src/CMakeFiles/scr_o.dir/scr_param.c.o
[ 32%] Building C object src/CMakeFiles/scr_o.dir/scr_path.c.o
[ 33%] Building C object src/CMakeFiles/scr_o.dir/scr_path_mpi.c.o
[ 35%] Building C object src/CMakeFiles/scr_o.dir/scr_reddesc.c.o
[ 36%] Building C object src/CMakeFiles/scr_o.dir/scr_reddesc_apply.c.o
[ 37%] Building C object src/CMakeFiles/scr_o.dir/scr_reddesc_recover.c.o
[ 38%] Building C object src/CMakeFiles/scr_o.dir/scr_split.c.o
[ 40%] Building C object src/CMakeFiles/scr_o.dir/scr_storedesc.c.o
[ 41%] Building C object src/CMakeFiles/scr_o.dir/scr_summary.c.o
[ 42%] Building C object src/CMakeFiles/scr_o.dir/scr_util.c.o
[ 43%] Building C object src/CMakeFiles/scr_o.dir/scr_util_mpi.c.o
[ 45%] Building C object src/CMakeFiles/scr_o.dir/tv_data_display.c.o
[ 46%] Building C object src/CMakeFiles/scr_o.dir/scr_flush_async_posix.c.o
[ 46%] Built target scr_o
Scanning dependencies of target scr
Linking C shared library libscr.so
[ 46%] Built target scr
Scanning dependencies of target scr-static
Linking C static library libscr.a
[ 46%] Built target scr-static
Scanning dependencies of target scr_base
[ 47%] Building C object src/CMakeFiles/scr_base.dir/scr_compress.c.o
[ 48%] Building C object src/CMakeFiles/scr_base.dir/scr_config.c.o
[ 50%] Building C object src/CMakeFiles/scr_base.dir/scr_config_serial.c.o
[ 51%] Building C object src/CMakeFiles/scr_base.dir/scr_dataset.c.o
[ 52%] Building C object src/CMakeFiles/scr_base.dir/scr_env.c.o
[ 53%] Building C object src/CMakeFiles/scr_base.dir/scr_err_serial.c.o
[ 55%] Building C object src/CMakeFiles/scr_base.dir/scr_filemap.c.o
[ 56%] Building C object src/CMakeFiles/scr_base.dir/scr_halt.c.o
[ 57%] Building C object src/CMakeFiles/scr_base.dir/scr_hash.c.o
[ 58%] Building C object src/CMakeFiles/scr_base.dir/scr_hash_util.c.o
[ 60%] Building C object src/CMakeFiles/scr_base.dir/scr_index_api.c.o
[ 61%] Building C object src/CMakeFiles/scr_base.dir/scr_io.c.o
[ 62%] Building C object src/CMakeFiles/scr_base.dir/scr_log.c.o
[ 63%] Building C object src/CMakeFiles/scr_base.dir/scr_meta.c.o
[ 65%] Building C object src/CMakeFiles/scr_base.dir/scr_param.c.o
[ 66%] Building C object src/CMakeFiles/scr_base.dir/scr_path.c.o
[ 67%] Building C object src/CMakeFiles/scr_base.dir/scr_util.c.o
[ 68%] Building C object src/CMakeFiles/scr_base.dir/tv_data_display.c.o
Linking C static library libscr_base.a
[ 68%] Built target scr_base
Scanning dependencies of target scr_copy
[ 70%] Building C object src/CMakeFiles/scr_copy.dir/scr_copy.c.o
Linking C executable scr_copy
[ 70%] Built target scr_copy
Scanning dependencies of target scr_crc32
[ 71%] Building C object src/CMakeFiles/scr_crc32.dir/scr_crc32.c.o
Linking C executable scr_crc32
[ 71%] Built target scr_crc32
Scanning dependencies of target scr_flush_file
[ 72%] Building C object src/CMakeFiles/scr_flush_file.dir/scr_flush_file.c.o
Linking C executable scr_flush_file
[ 72%] Built target scr_flush_file
Scanning dependencies of target scr_halt_cntl
[ 73%] Building C object src/CMakeFiles/scr_halt_cntl.dir/scr_halt_cntl.c.o
Linking C executable scr_halt_cntl
[ 73%] Built target scr_halt_cntl
Scanning dependencies of target scr_have_restart
[ 75%] Building C object src/CMakeFiles/scr_have_restart.dir/scr_have_restart.c.o
Linking C executable scr_have_restart
[ 75%] Built target scr_have_restart
Scanning dependencies of target scr_index
[ 76%] Building C object src/CMakeFiles/scr_index.dir/scr_index.c.o
Linking C executable scr_index
[ 76%] Built target scr_index
Scanning dependencies of target scr_inspect_cache
[ 77%] Building C object src/CMakeFiles/scr_inspect_cache.dir/scr_inspect_cache.c.o
Linking C executable scr_inspect_cache
[ 77%] Built target scr_inspect_cache
Scanning dependencies of target scr_log_event
[ 78%] Building C object src/CMakeFiles/scr_log_event.dir/scr_log_event.c.o
Linking C executable scr_log_event
[ 78%] Built target scr_log_event
Scanning dependencies of target scr_log_transfer
[ 80%] Building C object src/CMakeFiles/scr_log_transfer.dir/scr_log_transfer.c.o
Linking C executable scr_log_transfer
[ 80%] Built target scr_log_transfer
Scanning dependencies of target scr_nodes_file
[ 81%] Building C object src/CMakeFiles/scr_nodes_file.dir/scr_nodes_file.c.o
Linking C executable scr_nodes_file
[ 81%] Built target scr_nodes_file
Scanning dependencies of target scr_print_hash_file
[ 82%] Building C object src/CMakeFiles/scr_print_hash_file.dir/scr_print_hash_file.c.o
Linking C executable scr_print_hash_file
[ 82%] Built target scr_print_hash_file
Scanning dependencies of target scr_rebuild_xor
[ 83%] Building C object src/CMakeFiles/scr_rebuild_xor.dir/scr_rebuild_xor.c.o
Linking C executable scr_rebuild_xor
[ 83%] Built target scr_rebuild_xor
Scanning dependencies of target scr_retries_halt
[ 85%] Building C object src/CMakeFiles/scr_retries_halt.dir/scr_retries_halt.c.o
Linking C executable scr_retries_halt
[ 85%] Built target scr_retries_halt
Scanning dependencies of target scr_transfer
[ 86%] Building C object src/CMakeFiles/scr_transfer.dir/scr_transfer.c.o
Linking C executable scr_transfer
[ 86%] Built target scr_transfer
Scanning dependencies of target scrf
[ 87%] Building C object src/CMakeFiles/scrf.dir/scrf.c.o
Linking C shared library libscrf.so
[ 87%] Built target scrf
Scanning dependencies of target scrf-static
[ 88%] Building C object src/CMakeFiles/scrf-static.dir/scrf.c.o
Linking C static library libscrf.a
[ 88%] Built target scrf-static
Scanning dependencies of target test_api
[ 90%] Building C object examples/CMakeFiles/test_api.dir/test_common.c.o
[ 91%] Building C object examples/CMakeFiles/test_api.dir/test_api.c.o
Linking C executable test_api
[ 91%] Built target test_api
Scanning dependencies of target test_api_multiple
[ 92%] Building C object examples/CMakeFiles/test_api_multiple.dir/test_common.c.o
[ 93%] Building C object examples/CMakeFiles/test_api_multiple.dir/test_api_multiple.c.o
Linking C executable test_api_multiple
[ 93%] Built target test_api_multiple
Scanning dependencies of target test_ckpt_C
[ 95%] Building CXX object examples/CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o
Linking CXX executable test_ckpt_C
CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o: In function `MPI::Intracomm::Intracomm()':
test_ckpt.C:(.text._ZN3MPI9IntracommC2Ev[_ZN3MPI9IntracommC5Ev]+0x14): undefined reference to `MPI::Comm::Comm()'
CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o: In function `MPI::Intracomm::Intracomm(ompi_communicator_t*)':
test_ckpt.C:(.text._ZN3MPI9IntracommC2EP19ompi_communicator_t[_ZN3MPI9IntracommC5EP19ompi_communicator_t]+0x19): undefined reference to `MPI::Comm::Comm()'
CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o: In function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
test_ckpt.C:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x26): undefined reference to `ompi_mpi_cxx_op_intercept'
CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o:(.data.rel.ro._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `MPI::Win::Free()'
CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o:(.data.rel.ro._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `MPI::Datatype::Free()'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/test_ckpt_C] Error 1
make[1]: *** [examples/CMakeFiles/test_ckpt_C.dir/all] Error 2
make: *** [all] Error 2
`
the spack log is also attached here:
[spack-build.TXT](https://github.com/LLNL/scr/files/2166439/spack-build.TXT)

would greatly appreciate your help.
thank's.
Idan

**Comment by hjelmn** [comment]
Hmm. The C++ bindings were removed in MPI-3.0 in 2012. They are not built by default from Open MPI v3.0.0 and will be removed entirely in v5.0.0.

**Comment by Mosseridan** [comment]
So sould I install an earlier version of open mpi? And if so what veraion would you recommend?  What do you think i should do to fix this bug?

**Comment by adammoody** [comment]
Thanks for your help @hjelmn .

@Mosseridan , from the SCR side, we'll need to drop the test case that uses the C++ bindings for MPI and make a new release available for spack.  That will take us some time to put together.  We could get a fix to you faster if you don't mind building from the master branch.

Do you mind doing that?

Otherwise, I think a faster solution would be to build Open MPI with C++ bindings.  It looks to me like you're building with a system install of Open MPI:

```
/usr/lib64/openmpi
```

Based on the output here, it looks like the compile step worked, but it failed on the link step:

```
Linking CXX executable test_ckpt_C CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o: In functionMPI::Intracomm::Intracomm()':
test_ckpt.C:(.text._ZN3MPI9IntracommC2Ev[_ZN3MPI9IntracommC5Ev]+0x14): undefined reference to MPI::Comm::Comm()'
```

That can happen if it finds the C++ headers at compile time, but misses the necessary library with -l during link.  However, I do see earlier on that cmake found the Open MPI C++ library:

```
Found MPI_CXX: /usr/lib64/openmpi/lib/libmpi_cxx.so;
```

C++ compilers sometimes change how they mangle names across compiler versions.  If the Open MPI was built with one compiler, SCR might not be able to find the symbols at link time if it is built with a different compiler.  It looks like you're building SCR with 4.8.5.

Do you know what your Open MPI install was compiled with?

**Comment by adammoody** [comment]
Oh, in file you attached for the pure spack build, there are other clues.  There, I can see that it's building both SCR and Open MPI with the same compiler, and it has detected the Open MPI C++ library, but I can see that it's missing from the link line.  So that might be a problem in the SCR cmake files.  Let me check.

**Comment by gonsie** [comment]
The SCR CMake files don't link to the MPI C++ libraries (under the assumption that they deprecated). To fix this, add the following in the toplevel `CMakeLists.txt` file: 
```
IF(MPI_CXX_FOUND)
        INCLUDE_DIRECTORIES(${MPI_CXX_INCLUDE_PATH})
        LIST(APPEND SCR_EXTERNAL_LIBS ${MPI_CXX_LIBRARIES})
ENDIF(MPI_CXX_FOUND)
```
After the `INCLUDE(SetupMPI)` line.

**Comment by adammoody** [comment]
@hjelmn , so the test_ckpt.C file does not use the MPI C++ interface.  It is a C++ program, but it uses the MPI C interface.  However, it apparently picks up some C++ interface dependencies from some Open MPI headers.  I suppose we could fix this by linking in the Open MPI C++ library, but it's not clear whether that's the right thing to do.

Can you take a look and comment?

Here is the compile line from spack:

```
[ 85%] Building CXX object examples/CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o
cd /tmp/idanmos/spack-stage/spack-stage-lvrt51w9/scr-1.2.0/spack-build/examples && /home/idanmos/spack/lib/spack/env/gcc/g++   -I/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/openmpi-3.1.0-wihq6ns5dpzoja3hm5gvzpxijprv7wh7/include -I/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-64vg6e4evdrlqgx7iicwhu2hs7lv6gpz/include -I/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/dtcmp-1.1.0-z5diekaxgk42rxabqrq6v3hkp2a2g2c6/include -I/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/libyogrt-1.20-6-tcm7yxo23glyoabtxjceah4y3ghzpjx6/include -I/home/idanmos/spack/var/spack/stage/scr-1.2.0-u6em5mwaawncs5g4634fjiqo3kfwk2xd/scr-1.2.0/src -I/home/idanmos/spack/var/spack/stage/scr-1.2.0-u6em5mwaawncs5g4634fjiqo3kfwk2xd/scr-1.2.0/examples  -O2 -g -DNDEBUG -fPIE   -o CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o -c /home/idanmos/spack/var/spack/stage/scr-1.2.0-u6em5mwaawncs5g4634fjiqo3kfwk2xd/scr-1.2.0/examples/test_ckpt.C
```

And the link line, along with some of the errors:

```
[100%] Linking CXX executable test_ckpt_C
cd /tmp/idanmos/spack-stage/spack-stage-lvrt51w9/scr-1.2.0/spack-build/examples && /home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cmake-3.11.4-gify4cpe7hrtkaxrvrghwqdsb56zlci4/bin/cmake -E cmake_link_script CMakeFiles/test_ckpt_C.dir/link.txt --verbose=1
/home/idanmos/spack/lib/spack/env/gcc/g++  -O2 -g -DNDEBUG  -rdynamic CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o  -o test_ckpt_C -Wl,-rpath,/tmp/idanmos/spack-stage/spack-stage-lvrt51w9/scr-1.2.0/spack-build/src:/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/openmpi-3.1.0-wihq6ns5dpzoja3hm5gvzpxijprv7wh7/lib:/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-64vg6e4evdrlqgx7iicwhu2hs7lv6gpz/lib:/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/dtcmp-1.1.0-z5diekaxgk42rxabqrq6v3hkp2a2g2c6/lib:/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/libyogrt-1.20-6-tcm7yxo23glyoabtxjceah4y3ghzpjx6/lib ../src/libscr.so /home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/openmpi-3.1.0-wihq6ns5dpzoja3hm5gvzpxijprv7wh7/lib/libmpi.so /home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zlib-1.2.11-64vg6e4evdrlqgx7iicwhu2hs7lv6gpz/lib/libz.so /home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/dtcmp-1.1.0-z5diekaxgk42rxabqrq6v3hkp2a2g2c6/lib/libdtcmp.so /home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/libyogrt-1.20-6-tcm7yxo23glyoabtxjceah4y3ghzpjx6/lib/libyogrt.so 
CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o: In function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/openmpi-3.1.0-wihq6ns5dpzoja3hm5gvzpxijprv7wh7/include/openmpi/ompi/mpi/cxx/op_inln.h:122: undefined reference to `ompi_mpi_cxx_op_intercept'
CMakeFiles/test_ckpt_C.dir/test_ckpt.C.o: In function `MPI::Intracomm::Create_graph(int, int const*, int const*, bool) const':
/home/idanmos/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/openmpi-3.1.0-wihq6ns5dpzoja3hm5gvzpxijprv7wh7/include/openmpi/ompi/mpi/cxx/intracomm.h:25: undefined reference to `MPI::Comm::Comm()'
```

It seems like Open MPI may have pulled in references to C++ bindings because the app was compiler with a C++ compiler.

**Comment by Mosseridan** [comment]
Thank you @adammoody @gonsie and @hjelmn for your help. I have no problem compiling for the master branch.  And I would also like to try your approach @gonsie. I'll get to it first thing on sunday. If you have further Insighta I would love to hear them.

**Comment by Mosseridan** [comment]
@gonsie your suggestion worked for me. tough I would like to also be able to install using spack. with a future update that solves this issue. @adammoody I'd  love to get an update when such a patch is available. thank's for your help.

**Comment by Mosseridan** [comment]
I have 6 failed tests when running make test.
The failed tests are:

- 7:serial_test_api_multiple_start
- 8:serial_test_api_multiple_restart
- 10:parallel_test_api_multiple_start
- 11:parallel_test_api_multiple_restart

You can see LastTest.log here:
[LastTest.log](https://github.com/LLNL/scr/files/2176000/LastTest.log)

The output of all the failed tests is either a segmentation fault or something like this:
```
7/36 Testing: serial_test_api_multiple_start
7/36 Test: serial_test_api_multiple_start
Command: "/usr/bin/srun" "-ppbatch" "-t" "5" "-N" "1" "./test_api_multiple"
Directory: /home/idanmos/scr/scr_bld2/examples
"serial_test_api_multiple_start" start time: Jul 09 14:41 IDT
Output:
----------------------------------------------------------
[node023:25507] *** An error occurred in MPI_Type_get_extent
[node023:25507] *** reported by process [350945281,0]
[node023:25507] *** on communicator MPI_COMM_WORLD
[node023:25507] *** MPI_ERR_TYPE: invalid datatype
[node023:25507] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node023:25507] ***    and potentially your MPI job)
SCR v1.2.0: rank 0 on node023.rcl_hpc: Failed to record cluster name @ /home/idanmos/scr/scr/src/scr.c:608
SCR v1.2.0 WARNING: rank 0 on node023.rcl_hpc: Forcing copy type to SINGLE in redundancy descriptor 0 @ /home/idanmos/scr/scr/src/scr_reddesc.c:554
SCR v1.2.0: rank 0 on node023.rcl_hpc: scr_fetch_files: return code 1, 0.000183 secs
Init: Min 0.018966 s    Max 0.018966 s  Avg 0.018966 s
SCR v1.2.0: rank 0 on node023.rcl_hpc: Starting dataset timestep.1
srun: error: node023: task 0: Exited with exit code 3
<end of output>
Test time =   1.05 sec
----------------------------------------------------------
Test Failed.
"serial_test_api_multiple_start" end time: Jul 09 14:41 IDT
"serial_test_api_multiple_start" time elapsed: 00:00:01
----------------------------------------------------------
```
I am having a hard time understaning where and why do these tests fail and whether it is connected to the comiplation problem I had and it's fix.
I would appreciate your help in the manner.
Thanks in advance.

**Comment by adammoody** [comment]
PR under review:  https://github.com/LLNL/scr/pull/132

**Comment by adammoody** [comment]
I've lost track of the status on this particular issue, but I think it was resolved.  I'll close out this issue since the last PR was merged.

Let's open up a fresh issue or reopen this one if there is still a problem to be fixed.
