### ISSUE TITLE
Failed tests [An error occurred in MPI_Type_get_extent]

### ISSUE THREAD

**Issue by Mosseridan** [LLNL/scr#131]
I have 6 failed tests when running make test.
The failed tests are:

- 7:serial_test_api_multiple_start
- 8:serial_test_api_multiple_restart
- 10:parallel_test_api_multiple_start
- 11:parallel_test_api_multiple_restart

You can see LastTest.log here:
[LastTest.log](https://github.com/LLNL/scr/files/2176000/LastTest.log)

The output of all the failed tests is either a segmentation fault or something like this:
```
7/36 Testing: serial_test_api_multiple_start
7/36 Test: serial_test_api_multiple_start
Command: "/usr/bin/srun" "-ppbatch" "-t" "5" "-N" "1" "./test_api_multiple"
Directory: /home/idanmos/scr/scr_bld2/examples
"serial_test_api_multiple_start" start time: Jul 09 14:41 IDT
Output:
----------------------------------------------------------
[node023:25507] *** An error occurred in MPI_Type_get_extent
[node023:25507] *** reported by process [350945281,0]
[node023:25507] *** on communicator MPI_COMM_WORLD
[node023:25507] *** MPI_ERR_TYPE: invalid datatype
[node023:25507] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node023:25507] ***    and potentially your MPI job)
SCR v1.2.0: rank 0 on node023.rcl_hpc: Failed to record cluster name @ /home/idanmos/scr/scr/src/scr.c:608
SCR v1.2.0 WARNING: rank 0 on node023.rcl_hpc: Forcing copy type to SINGLE in redundancy descriptor 0 @ /home/idanmos/scr/scr/src/scr_reddesc.c:554
SCR v1.2.0: rank 0 on node023.rcl_hpc: scr_fetch_files: return code 1, 0.000183 secs
Init: Min 0.018966 s    Max 0.018966 s  Avg 0.018966 s
SCR v1.2.0: rank 0 on node023.rcl_hpc: Starting dataset timestep.1
srun: error: node023: task 0: Exited with exit code 3
<end of output>
Test time =   1.05 sec
----------------------------------------------------------
Test Failed.
"serial_test_api_multiple_start" end time: Jul 09 14:41 IDT
"serial_test_api_multiple_start" time elapsed: 00:00:01
----------------------------------------------------------
```
I am having a hard time understanding where and why do these tests fail and whether it is connected to the [compilation problem I had and it's fix](https://github.com/LLNL/scr/issues/130).
I would appreciate your help in the manner.
Thanks in advance.

**Comment by adammoody** [comment]
Thanks for the report @Mosseridan.  I'll take a look.

**Comment by adammoody** [comment]
Building by hand, most of the tests pass for me.  A couple tests with interpose fail, but it seems like all of the tests that are failing for you pass for me.

The "invalid dataype" message could show up if an MPI app / library are mixing different MPI implementations, as the constants in the headers are defined with different values, so perhaps the build is mixing MPI libs.

Are you building by running cmake or are you using spack?

Are you able to collect a stack trace at the point where the MPI_Type_get_extent error message is thrown?

**Comment by Mosseridan** [comment]
Hi @adammoody. I built scr using cmake. after after playing a bit with MPI and compiler versions the 10:parallel_test_api_multiple_start and 11:parallel_test_api_multiple_restart test do complete successfully tough for some reasons the the 7:serial_test_api_multiple_start and 8:serial_test_api_multiple_restart test still fail as before. I am guessing this has something to do with the fact that this test runs the with a single MPI process and at some point executes some MPI communication method that isn't valid with only single process.

The fact that the parallel tests past means that i can start working with scr (really liking it so far :) ).
Tough it would be nice to know why the same test fails on a serial execution while succeeding in a parallel one, I am marking this issue as resolved for me.
