### ISSUE TITLE
Interest in mcrEngine with SCR

### ISSUE THREAD

**Issue by Mosseridan** [LLNL/scr#135]
Hi.
I have been looking around for a optimal ways to merge and compress SCR checkpoints in order to reduce DFS overhead, and stumbled upon the impressive research you made with  [“mcrEngine: A Scalable Checkpointing System using Data-aware Aggregation and Compression”](https://dl.acm.org/citation.cfm?id=2389020).

This research looks very promising and I would be interested in having mcrEngine integrated into SCR.
Is this something planed for future SCR versions?

Meanwhile I would love to have mcrEngines source code to play with if at all possible. any documentation on integrating checkpoint aggregation with MPI_IO, HDF5  and SCR will be highly appreciated.

Thank you.
Idan.

**Comment by kathrynmohror** [comment]
Hi Idan,

We don't have immediate plans to make this part of SCR. For now, I recommend that you reach out to the lead author on the work: Tanzima Islam https://cse.wwu.edu/computer-science/islamt2

Kathryn

**Comment by Mosseridan** [comment]
Thank you.
