### ISSUE TITLE
Down node detection on LSF has wrong node count

### ISSUE THREAD

**Issue by CamStan** [LLNL/scr#143]
### Issue
`LSB_DJOB_HOSTFILE` also contains the launch node.

https://github.com/LLNL/scr/blob/54f8f86a02f8e6df7ea2d622a1f42c0da0663b83/scripts/LSF/scr_env.in#L81

When it is used to generate a `nodelist` without filtering out the launch node:
https://github.com/LLNL/scr/blob/54f8f86a02f8e6df7ea2d622a1f42c0da0663b83/scripts/LSF/scr_jsrun.in#L94-L96

SCR thinks one more node is needed than actual, and that one more node is available in the event of a restart.

### How to Replicate
Configure JSM to allow jsrun to launch new jobs after a node failure in an allocation by setting FAULT_TOLERANCE=1 in a private ~/.jsm.conf file:
```
# Create a custom jam.conf file to be used in your jobs
cp /opt/ibm/spectrum_mpi/jsm_pmix/etc/jsm.conf ~/.jsm.conf
 
# Then modify your ~/.jsm.conf to uncomment
FAULT_TOLERANCE = 1
```

Allocate two nodes and run `src_jsrun` to identify them:
```
user@butte5 bin $ ./scr_jsrun -r 1 ./mpihostname
scr_jsrun: Started: Thu Apr  4 14:28:23 PDT 2019
scr_jsrun: RUN 1: Thu Apr  4 14:28:23 PDT 2019
0 of 2 on butte17
1 of 2 on butte18
scr_jsrun: $SCR_RUNS exhausted, ending run.
scr_jsrun: Ended: Thu Apr  4 14:28:23 PDT 2019
```
Then run again on a single node to identify which is the default:
```
user@butte5 bin $ ./scr_jsrun -r 1 -n1 ./mpihostname
scr_jsrun: Started: Thu Apr  4 14:49:41 PDT 2019
scr_jsrun: RUN 1: Thu Apr  4 14:49:41 PDT 2019
0 of 1 on butte17
scr_jsrun: $SCR_RUNS exhausted, ending run.
scr_jsrun: Ended: Thu Apr  4 14:49:41 PDT 2019
```
Have someone with superpowers kill that node for you and **wait at least 1 minute, if not more, before running again.** There is a `jsrun` bug that will cause a hang if you try too soon. While waiting, set the debug variable to see what is happening.
```
export SCR_DEBUG=1
```
**After at least 1 minute**, run again:
```
user@butte5 bin $ ./scr_jsrun -r 1 -n1 ./mpihostname
+ ⋮
scr_jsrun: Started: Thu Apr  4 15:03:58 PDT 2019
+ ⋮
++ /<bindir>/scr_env --nodes
+ nodelist=butte17,butte18,butte5
+ '[' 0 -eq 0 ']'
+ SCR_NODELIST=butte17,butte18,butte5
+ '[' -z butte17,butte18,butte5 ']'
+ export SCR_NODELIST
+ ⋮
++ /<bindir>/scr_list_down_nodes --free
butte17: ssh: connect to host butte17 port 22: Connection timed out
pdsh@butte5: butte17: ssh exited with exit code 255
+ down_nodes=butte17
+ '[' butte17 '!=' '' ']'
+ /<bindir>/scr_list_down_nodes --free --reason
butte17: ssh: connect to host butte17 port 22: Connection timed out
pdsh@butte5: butte17: ssh exited with exit code 255
butte17: Failed to pdsh echo UP
+ ⋮
NNODES=-1 RUNTIME=0 FAILED=butte17'
+ ⋮
++ /<bindir>/scr_glob_hosts --count --hosts butte17,butte18,butte5
+ num_needed=3
+ '[' -n 1 ']'
+ num_needed=1
++ /<bindir>/scr_glob_hosts --count --minus butte17,butte18,butte5:butte17
+ num_left=2
+ '[' 2 -lt 1 ']'
+ exclude_hosts=--exclude_hosts=butte17
+ ⋮
scr_jsrun: RUN 1: Thu Apr  4 15:04:19 PDT 2019
+ jsrun --exclude_hosts=butte17 -n 1 -r 1 ./mpihostname
0 of 1 on butte18
+ ⋮
scr_jsrun: $SCR_RUNS exhausted, ending run.
+ ⋮
scr_jsrun: Ended: Thu Apr  4 15:04:19 PDT 2019
```
Notice the launch node is included in the `SCR_NODELIST` and that `num_needed=3` originally and `num_left=2` after the failed node was accounted for. But we only allocated 2 nodes to begin with.
 
Had `SCR_MIN_NODES` been set to 2, this would still think it has enough nodes to try again.

**Comment by adammoody** [comment]
Thanks, @CamStan !  One small detail, rather than setting FAULT_TOLERANCE=2, you mean to say setting SCR_MIN_NODES=2

**Comment by CamStan** [comment]
Oops! Changed it.

**Comment by adammoody** [comment]
Should be fixed with https://github.com/LLNL/scr/commit/a8fe43f2a85de53fd650ce44026f7858185f1411
