### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by mShining** [LLNL/scr#144]
In _Quickstart_ section:

![image](https://user-images.githubusercontent.com/11251757/58848314-ac0abc80-86b8-11e9-9036-fd82cc2bf7b3.png)

`cmake -DCMAKE_INSTALL_PREFIX=../install ../scr`
should be
`cmake -DCMAKE_INSTALL_PREFIX=../install ../src`

**Comment by adammoody** [comment]
Thanks for reporting this, @mShining !

**Comment by adammoody** [comment]
Oh, wait.  Looking at the commands here, I think it should be ```../scr``` after all.  The git clone of scr.git would create an ```scr``` directory at the same level as the ```build``` directory.  Then on the cd into build, we'd need ```../scr``` to refer back to the top-level scr git clone directory.

Does this not work for you?

**Comment by mShining** [comment]
You're right. It's my mistake. I've gone to the root dir of the project by running `cd scr` before running `mkdir build`. So in my case, there is no "scr" but a "src" in "../". It made me think it's a typo.

Please fogive my carelessness. And thank you for your kind reminder. @adammoody
