### ISSUE TITLE
Refactor scr async flush code to make it easier to add new vendor-specific APIs

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#15]
Let's go with @gonsie 's approach for factorizing vendor-specific async flush methods.

**Comment by becker33** [comment]
scr_flush_async_init is one of the functions that need to be refactored. Related to bug in transfer daemon.

**Comment by gonsie** [comment]
Declaring this done once #126 is merged.

**Comment by adammoody** [comment]
AXL is the result of this refactoring.
