### ISSUE TITLE
Switch to components branch

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#154]
The SCR project is officially switching to the components branch. To do this with the least amount of disruption (and possibility for mucking things up with git), we are adopting the following:

1. A new branch, named 'legacy', will be created where the master branch is now. The master branch label will remain for a short while and will be deleted once we are sure the conversion is a success.
2. A new branch, named 'develop', will be created where the components branch is now. New work should happen off of this branch and developers should submit PRs against it. The components branch label will remain for a short time. 

Current Progress
- [x] add develop branch to repo, at components
- [x] add legacy branch to repo, at master
- [x] make develop the default branch in GitHub
- [x] update spack package
- [x] update documentation on building with spack (in `doc-dev/rst/developers/testing_bamboo.rst`)
- [x] review outstanding PRs and branches.
- [x] make sure readthedocs is building from develop
- [x] update documentation to include the component dependencies
  - `README.md`
  - `doc/rst/users/quick.rst`
  - `doc/rst/users/build.rst`

ping @LLNL/scr-developers 

---
Edit: must update docs to depend on components

While updated the documentation, here is a list of lost features moving from legacy to components.  This list will grow as we think of other items.  The eventual goal is to support all of these parameters again, but there is work to do so they can be passed from SCR down to the respective components.  These will show up in the SCR parameters section, and perhaps scattered references to various params through the rest of the document.
- [ ] ability to customize redundancy sets, e.g., SCR_XOR_SET_SIZE
- [ ] CRC checking on files, e.g., during a flush/fetch or encoding
- [ ] anything to do with fetch/flush, which is now moved to FILO/AXL, e.g., SCR_PRESERVE_DIRECTORIES, SCR_FILE_BUF_SIZE, SCR_FLUSH_WIDTH
- [ ] catch all: go through each parameter one-by-one

**Comment by tonyhutter** [comment]
So why not rename `components` to `master`?  Most git project use `master` for their development branch.  Why break convention?  If the conversion is not a success then we can always force push `legacy` back into `master` as if nothing ever happened.

**Comment by kathrynmohror** [comment]
We made a decision to name it develop to explicitly divorce it from master -- to make sure that anyone that tries to do operations on master encounters an error. In the future, we can change the name of develop to master. We're just trying to avoid confusion/problems in the near term.

**Comment by tonyhutter** [comment]
There is an alternate way we can do this switchover that will cause zero disruption/confusion to the user.  We can simply git merge the `components` branch into `master`  This works for me cleanly:

1. git checkout master

2. git revert 68414920bf40f85afce8c88c9b042ba30a928f49. 
	- Revert "Fix compile error when using BBAPI", since it's not applicable to components, and may cause conflicts.

3. git merge components

Here's what the switchover would look like to the user:
```
$ git clone https://github.com/tonyhutter/scr.git user-scr

$ cd user-scr/

~/user-scr $ git branch
* master

# User is on our old master branch

~/user-scr $ git log --oneline | head -n 5
6841492 Fix compile error when using BBAPI
5989bc9 whitespace matters?
59566b9 @camstan suggested changes from #145
e4e20f8 Dev test docs (#145)
ddfa459 test_api: add --path to disable SCR and write to PFS

# in another window, components is merged into master

# user pulls in the components changes like normal

~/user-scr $ git pull
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 18 (delta 0), reused 2 (delta 0), pack-reused 16
Unpacking objects: 100% (18/18), done.
From https://github.com/tonyhutter/scr
   6841492..1421fd3  master     -> origin/master
Updating 6841492..1421fd3
Fast-forward
 CMakeLists.txt                 |   65 ++++++-
 README.md                      |    6 +-
 bootstrap.sh                   |  108 +++++++++++
 cmake/FindAXL.cmake            |   31 +++
 cmake/FindBBAPI.cmake          |    4 +-
 cmake/FindER.cmake             |   31 +++
 cmake/FindFILO.cmake           |   31 +++

...

 delete mode 100644 src/tv_data_display.c
 delete mode 100644 src/tv_data_display.h

# components is there:

$ git log --oneline | head -n 5
1421fd3 Merge branch 'components'
e73a138 Revert "Fix compile error when using BBAPI"
ec366b7 whitespace matters?
70d8fcf @camstan suggested changes from #145
1c6761f Dev test docs (#145)
```

**Comment by kathrynmohror** [comment]
Thanks for that Tony! I believe the work is already done though so perhaps next time we have a large divergence we can try to do it properly.

**Comment by gonsie** [comment]
See spack/spack#14931

**Comment by tonyhutter** [comment]
SCR has been using the components branch for awhile now.  We can probably close this issue.

**Comment by adammoody** [comment]
Will close this one out.  There are still items being worked, but we have separate issues open for those.
