### ISSUE TITLE
Integrate SCR into HACC IO benchmark

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#16]
Integrate SCR into HACC IO and collect feedback on any issues / complexities with doing that to inform future SCR API changes.

**Comment by c-a-h** [comment]
@adammoody I'm not sure if you were aware but we actually did an initial port of HACCIO to SCR. I can point you to our source code if you're interested.

**Comment by c-a-h** [comment]
I actually even somewhat rewrote HACCIO so it would have iteration loops and could take advantage of SCRs restart capability

**Comment by gonsie** [comment]
@c-a-h It would be great to look at your HACCIO+SCR implementation.

Also, I had heard that https://github.com/glennklockwood/hacc-io may be out-of-date with what the HACC code is currently doing w.r.t. I/O. GenericIO (http://trac.alcf.anl.gov/projects/genericio) is supposedly more current.

**Comment by c-a-h** [comment]
here are the changes I had made.  Please feel free to reach out to me if you have any questions
https://git.hpdd.intel.com/?p=coral/cppr.git;a=commit;h=15697f2fe5d31293e64738a977bdfb7dd881ed15

I was working based upon an internal mirror we had created for HACCIO, so this may not even be fully reflective of that github repo you pointed to.  

Thanks for the pointer to GenericIO.  I will take a look

**Comment by c-a-h** [comment]
By the way, those HACCIO code changes are what we used in our live demo to ANL back in October or November of last year to showcase SCR along with our CPPR and PMIx changes.

**Comment by adammoody** [comment]
@gonsie Can you tell how significant the changes would be in the genericio version compared to HACCIO?

**Comment by adammoody** [comment]
Thanks for your input on this @c-a-h .  We don't have the same driving need when this was opened, so we'll close it out.  And knowing you had this working is reassuring that the API was sufficient.

**Comment by Alessandro-Barbieri** [comment]
where do you download cppr?

**Comment by adammoody** [comment]
Hi, @Alessandro-Barbieri .  Perhaps @c-a-h can confirm, but I don't believe CPPR is under active development.  I also can't find the CPPR source repo with a quick search.  Perhaps there is an archived copy of it somewhere, but I'm not sure.

**Comment by c-a-h** [comment]
I'll defer to folks still at Intel. My previous public links aren't working anymore for CPPR.

**Comment by jolivier23** [comment]
I have an archived copy in my personal github but it is no longer an active project.   I think SCR could remove any cppr references.
