### ISSUE TITLE
update scaling chart in documentation

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#161]
we have newer numbers from a scaling run on Lassen... we need to put that chart into rtd.

**Comment by CamStan** [comment]
@kathrynmohror, do your commits https://github.com/LLNL/scr/commit/b79ded98a5d41b6bc1969fc21b3c853a74bb4a98 and https://github.com/LLNL/scr/commit/a67a0404cdafa37ccf33c461bcec395e742d4eea complete this?

**Comment by kathrynmohror** [comment]
Yes!
