### ISSUE TITLE
Update build docs to include new components

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#170]
The steps needed to build with the components are not in our current build documentation.  We should update this to list the cmake flags for the component install paths (filo, axl, spath, etc.).

https://scr.readthedocs.io/en/latest/users/build.html#cmake

Also, let's point people to the page on how to configure a spack clone with a custom packages.yaml.  In practice, I always find that to be a necessary step, and it'd be nice to give people a heads up before they discover that detail the hard way.
```
git clone spack
--> create a packages.yaml for your machine and any other spack config <--
spack install scr
```
https://scr.readthedocs.io/en/latest/users/build.html#spack

**Comment by gonsie** [comment]
Was this completed by #224 ? Or is there something left to do?

**Comment by adammoody** [comment]
The docs aren't done yet with respect to changes needed for the ECP components.  In particular, I'm not sure that the instructions we list in our Quick Start and Compile/Link sections are valid.

We have the following outstanding items:
- There are 4 TODO items in the quick start section (2 for spack and 2 for cmake)
  - https://github.com/LLNL/scr/blob/develop/doc/rst/users/quick.rst#building-the-scr-test_api-example
  - https://github.com/LLNL/scr/blob/develop/doc/rst/users/quick.rst#running-the-scr-test_api-example
- Need to verify the compile and link flags we list in the Integrate section (both spack and cmake install of SCR)
  - https://github.com/LLNL/scr/blob/develop/doc/rst/users/integration.rst#building-with-the-scr-library

We could close this particular issue, but we should create new issues to track those outstanding items.

**Comment by adammoody** [comment]
I created new issues for these, so I'll close out this issue:
https://github.com/LLNL/scr/issues/301
https://github.com/LLNL/scr/issues/302
https://github.com/LLNL/scr/issues/303
https://github.com/LLNL/scr/issues/304
