### ISSUE TITLE
Update veloc components to be configurable by SCR

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#172]
A number of SCR configuration settings should be applied to components, which are currently hard-coded with particular values.  From the config page in readthedocs, the following may not be currently supported.  In some cases, it may make more sense to drop the config settings.

Components | Name | Default | Description
-- | -- | -- | --
er/reddset | SCR_SET_SIZE | 8 | Specify the minimum number of processes to include in an XOR set. Increasing this value decreases the amount of storage required to cache the checkpoint data. However, higher values have an increased likelihood of encountering a catastrophic error. Higher values may also require more time to reconstruct lost files from redundancy data.
filo | SCR_FETCH_WIDTH | 256 | Specify the number of processes that may read simultaneously from the parallel file system.
filo | SCR_FLUSH_WIDTH | 256 | Specify the number of processes that may write simultaneously to the parallel file system.
filo/axl | SCR_FLUSH_ASYNC_BW | 0.0 | Max allowed network bandwidth on flush.
filo/axl | SCR_FLUSH_ASYNC_PERCENT | 0.0 | Max allowed CPU percent usage on flush.
er/reddset/shuffile | SCR_MPI_BUF_SIZE | 131072 | Specify the number of bytes to use for internal MPI send and receive  buffers when computing redundancy data or rebuilding lost files.
filo/axl | SCR_FILE_BUF_SIZE | 1048576 | Specify the number of bytes to use for internal buffers when copying files between the parallel file system and the cache.
er/reddset | SCR_CRC_ON_COPY | 0 | Set to 1 to enable CRC32 checks when copying files during the redundancy scheme.
filo/axl | SCR_CRC_ON_FLUSH | 1 | Set to 0 to disable CRC32 checks during fetch and flush operations.

**Comment by adammoody** [comment]
@rhaas80 , here is a list of config settings to start with that would need to affect how the components are configured.  In some cases, we might opt to just drop some of these, so consider them all open to discussion for that.

**Comment by rhaas80** [comment]
thank you. I will give this a try.

**Comment by adammoody** [comment]
Thanks @rhaas80 .  The set_size parameter is probably the most used of all of these, so it would be good to include that one early.

**Comment by rhaas80** [comment]
The veloC components are a bit a inconsistent in their "init" functions. Eg:

* `redset_init()` is lowercase and actually uses no arguments but is declared as varargs
* `Filo_Init()` is CamelCase and actually uses no arguments but is declared as varargs
* `ER_Init(const char* conf_file)` but does not use `conf_file` at all

**Comment by adammoody** [comment]
We've added a few more params to AXL recently:
https://github.com/ECP-VeloC/AXL/blob/c1984e5f337626e5f4680d780b95512b6d1328ef/src/axl.c#L171
```
AXL_DEBUG
AXL_MKDIR
AXL_COPY_METADATA
```
We're currently setting those by environment variables from AXL_Init.  Eventually, I think some of those would be good to set per transfer, but they are all global settings in the library right now.

**Comment by rhaas80** [comment]
I'll add them to the config interface. Will be nice to have both values to pass along to lower level libraries and native AXL settings.

**Comment by rhaas80** [comment]
usage graph:

scr: filo, er
filo: AXL
er: redset, shuffile
redset:
AXL:

**Comment by rhaas80** [comment]
Components that are configurable:

filo: https://github.com/ECP-VeloC/filo/commit/140dad06a5ec75551e5fd16c9fdea6baa1230c67
er: https://github.com/ECP-VeloC/er/commit/5ca81f2d84ca38b5e3ea03772e89700457b57921
AXL: https://github.com/ECP-VeloC/AXL/commit/9ccb313d737d966194f751b4e6ece448a877309c
redset: https://github.com/ECP-VeloC/redset/commit/2555252304b0c17028cfe5fccb831f422040ee8e
shuffile: https://github.com/ECP-VeloC/shuffile/commit/0feb3fabd5ac0b4c0abbc38605966a5469dccb4f
