### ISSUE TITLE
setting SCR_RESOURCE_MANAGER to an unexpected value in cmake leads to strange error message

### ISSUE THREAD

**Issue by rhaas80** [LLNL/scr#203]
When one sets SCR_RESOURCE_MANAGER to an unexpected value, for example "None", then cmake aborts with an unhelpful error message:

```#bash
$ cmake -DCMAKE_INSTALL_PREFIX=../install  -DSCR_RESOURCE_MANAGER=None
-- MPI C Compile Flags:  -pthread
-- MPI C Include Path:   /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI C Link Flags:     -pthread
-- MPI C Libraries:      /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI CXX Compile Flags: -pthread
-- MPI CXX Include Path:  /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI CXX Link Flags:    -pthread
-- MPI CXX Libraries:     /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI Executable:       /usr/bin/mpiexec
-- MPI Num Proc Flag:    -n
-- Using MPI Fortran header: mpif.h
CMake Error: File /scr_run.in does not exist.
CMake Error at scripts/CMakeLists.txt:5 (CONFIGURE_FILE):
  CONFIGURE_FILE Problem configuring file
Call Stack (most recent call first):
  scripts/CMakeLists.txt:67 (SCR_INSTALL_BIN)
```
This is due to `scripts/CMakeLists.txt`  not having any check that `SCR_RESOURCE_MANAGER` is actually among the supported values.

**Comment by adammoody** [comment]
@rhaas80 and @gonsie , did you find if there is an option for this?

**Comment by adammoody** [comment]
According to this post:

https://blog.kitware.com/constraining-values-with-comboboxes-in-cmake-cmake-gui/

it sounds like we have to code up a check manually:
> For completeness, I should also mention that there is no code in cmake itself to enforce the constraint that a cache entry must have one of the values mentioned in its corresponding STRINGS property. After editing by cmake-gui, the edited cache entry will have one of the listed values, but if a user runs cmake -Dentry=blah  then the entry will have value blah regardless of the listed values in the STRINGS  property. If you wish to have fully bulletproof, “this value must be in this list” validation, then you must write code in your CMakeLists.txt file to enforce it.

**Comment by adammoody** [comment]
This post helps:

https://stackoverflow.com/questions/23323147/best-way-to-check-with-cmake-whether-list-containts-a-specific-entry

**Comment by adammoody** [comment]
@rhaas80 , thanks for bringing this up.  I added a check for SCR_RESOURCE_MANAGER, SCR_FILE_LOCK, and a few of the LOG options that take either 0 or 1.
