### ISSUE TITLE
Tests failing in "make test"

### ISSUE THREAD

**Issue by robertkb** [LLNL/scr#211]
On catalyst, the serial_test_api_multiple_start and  serial_test_api_multiple_restart tests are failing. All other tests are passing.

**Comment by robertkb** [comment]
I am investigating.

**Comment by adammoody** [comment]
There is a known bug in DTCMP that bites in the "serial multiple" test.  In this case, there is a single process, and it writes 0 checkpoint files.  To support shared-file writes, we are now calling DTCMP_Rankv_strings from SCR on each checkpoint, but that function did not correctly handle a 0 count.

This is fixed upstream in DTCMP, but I still need to make a release that includes that fix.

**Comment by robertkb** [comment]
I will pause my investigation, until the dtcmp fix is in.

**Comment by adammoody** [comment]
Related issue https://github.com/LLNL/dtcmp/issues/4

**Comment by adammoody** [comment]
Cut a new DTCMP release: https://github.com/LLNL/dtcmp/releases/tag/v1.1.1

You might be able to test with this now.

I'll also update the dtcmp spack package next.

**Comment by adammoody** [comment]
@robertkb , I think you mentioned this is fixed, but if not, let's reopen this issue.

**Comment by robertkb** [comment]
It was fixed. I'll check it again today, but I'm pretty sure we can leave it closed.
