### ISSUE TITLE
Setting SCR_PREFIX with SCR_Config

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#218]
I've run into a catch-22 here.  I'm guessing that a lot of codes might want to use SCR_Config to set SCR_PREFIX at run time, but we can't do that just yet.

Motivation:
Some apps provide options to let the user specify the output directory in which to write its checkpoints.  This might look something like:
```
srun -n 2 myprog --output /my/output/directory
```
This often means the user is running the application from one directory, but writing checkpoints somewhere else.  When using SCR, they'd typically need to set SCR_PREFIX to specify that same output directory.  Rather than ask their users to manually set SCR_PREFIX before launching the job, developers might prefer to set SCR_PREFIX for them from within the app.  The natural way to do that is to set SCR_PREFIX through SCR_Config.

So that means instead of asking their users to do:
```
export SCR_PREFIX=/my/output/directory
srun -n 2 myprog --output /my/output/directory
```
They could handle this for them from within the application:
```
srun -n 2 myprog --output /my/output/directory
# myprog then calls SCR_Config("SCR_PREFIX=/my/output/directory") before calling SCR_Init
```
This way, the user interface that the application developers expose to their users is the same -- there is no additional step to set SCR_PREFIX before launching the job.  This also eliminates the chance that the user introduces a typo by having to type the output path in two places.

Note setting SCR_PREFIX at run time does prohibit one from using the SCR scripts, since the scripts that run before the job can't see the new SCR_PREFIX value.  However, that may still be a common trade off people are willing to make.

Problem:
However, the problem is that our SCR_Config implementation needs to know SCR_PREFIX before it executes.  It looks up both the user config file and the app config file using the SCR_PREFIX value.

Possible solutions:
- Require developer to set SCR_PREFIX through a call to ```setenv``` instead of SCR_Config and to require this before they ever call SCR_Config.  This probably works fine, but it feels like a hack.
- Add a new ```SCR_Config_init(const char* prefix)``` function that takes the prefix directory as an argument to be called before any SCR_Config call.  This would also let us move the scr_param_init call out of SCR_Config.  Do we need to worry about other special parameters in a similar way?
- Allow users to set values with SCR_Config but not query them before calling SCR_Init.  With this, we just accumulate settings in a hash that SCR_Init will process during scr_get_params.  We could then optionally allow a user to query values with SCR_Config after SCR_Init but not set them.  Alternatively, we could allow a user to query values that they previously set with SCR_Config before SCR_Init, but we couldn't account for settings from other sources like the user config file.  Querying a value before SCR_Init is difficult, because we need to read the user and app config files for a query, but we can't read those files until we know SCR_PREFIX.

Another thing to consider is how long to persist parameters that have been set with SCR_Config.  For any parameter set with SCR_Config, the value is written to the file stored at ```${SCR_PREFIX}/.scr/app.conf```.  This file persists after a job exits so that the scripts that may run after the job can use the same settings from the job.  The file also persists across multiple runs of the same job, so that the settings will be applied to any restarted job.  One can imagine this as being the desired behavior in some cases, whereas the user may want to restart with a clean slate in other cases.

We could include an option for SCR to delete the file on new runs.  If we go with ```SCR_Config_init(const char* prefix)```, we could provide an option to delete the file, or just delete the file automatically.  If we do not have an init call, we could delete the file the first time SCR_Config is called in each run.

**Comment by rhaas80** [comment]
Right now (or at least when I wrote` SCR_Config`) you cannot query after `SCR_Init()` either because `scr_param_finalize` (or whatever its name) tears down the hashes to everything just returns as "not set".

I think that querying is also the only reason why `SCR_Config` used `SCR_PREFIX` (to read the user config and app config files). Otherwise `SCR_Config` calls just populate the app hash keyval structure but do not rely on anything else being present.

**Comment by adammoody** [comment]
Looking for locations where SCR_PREFIX might be accessed:

https://github.com/LLNL/scr/blob/70c048b7d79c3cc383bcf9664112b59dab97d0b0/scripts/common/scr_prefix.in#L9

**Comment by rhaas80** [comment]
In the scripts? scr_param.in ie the Perl module giving access to parameters also does so (and a couple more). If we want a consistency check in the C code that no script using SCR_PREFIX ran before the C code then those scripts (well all of them most likely to make sure one does not miss any) will have to record their $prefix value and they and the C code must report an error if this value differs from what is going to be used by them. The natural place to store that information is, at least to me, the .scr directory ... which needs to know SCR_PREFIX. So some thought may be required.

**Comment by adammoody** [comment]
Resolved with https://github.com/LLNL/scr/pull/424
