### ISSUE TITLE
LSF: how to get remaining time in job allocation?

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#24]

**Comment by becker33** [comment]
We can do this with ugly parsing and without being able to account for dynamic changes in allocation length, or we can push on IBM to get the option into LSF/CSM.

**Comment by becker33** [comment]
Notes for later when we get to implementation:

```
$ bjobs -l <number> > jobinfo
$ cat jobinfo | grep -A1 "RUNLIMIT"
$ cat jobinfo | grep "Started [[:digit:]]\+ Task(s) on Host(s)"
```

We can clean up this process and use it similarly to how we get time remaining through MOAB on MOAB/ALPS systems.

**Comment by adammoody** [comment]
Thinking about it more, an API call could will probably take months before it's available.  So that users can get by in the meantime, please go ahead and and create something based on the bjobs output.  Let's handle cases in which a job may end in seconds, minutes, hours, and days.  From that and the current system time, you could compute the seconds-since-epoch time for the job end time, which we could then read into SCR via an environment variable.  I know you've been thinking about this, so feel free to go with a different implementation if you prefer.

**Comment by adammoody** [comment]
Some useful info:
bjobs -o "time_left"
https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/api_reference/index.html
int runTime
int duration

**Comment by adammoody** [comment]
Got this going on the lsf branch

**Comment by adammoody** [comment]
Should be supported with https://github.com/LLNL/scr/commit/ea7b71d05d842ce702989113fb5f681ea670e89a
