### ISSUE TITLE
libyogrt spack scheduler selection

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#253]
libyogrt must be built with different flags depending on the resource manager.  Should libyogrt have an ``scheduler=lsf`` option?

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/libyogrt/package.py

We should check that libyogrt builds (and works) correctly for both SLURM and LSF.  That is, when used in a resource allocation, it should correctly report the amount of remaining time.

Also, then we should be sure that we specify the proper libyogrt spec in the scr spack recipe depending on the resource manager the user selects.  I think the configure auto-detects the resource manager by looking for libraries, which may work.  However, there is also a config file that might need to be updated as part of the install:

https://github.com/LLNL/libyogrt/blob/master/yogrt.conf.example

**Comment by adammoody** [comment]
For ``scheduler=lsf``, do we need to list ``lsf`` as an option here?
https://github.com/spack/spack/blob/2a8dba48dad0d133eb7435df6ab318c3722a8d6e/var/spack/repos/builtin/packages/libyogrt/package.py#L36

**Comment by adammoody** [comment]
It seems scr is trying to link with libyogrt.a for some reason, which isn't normally installed by spack:
https://github.com/spack/spack/issues/17894

To fix this, we should either fix scr to link with libyogrt.so or add ``libyogrt+static`` to the scr spack package.

**Comment by adammoody** [comment]
I verified that a spack-installed libyogrt on quartz (SLURM) does not work out of the box:
```
>>: cat grt.c
#include <stdlib.h>
#include <stdio.h>
#include "yogrt.h"
int main (int argc, char* argv[])
{
  long int secs = yogrt_remaining();
  printf("%lu\n", secs);
  return 0;
}

# allocate a node in pdebug, which has an hour time limit
salloc -N1 -ppdebug

# try spack install
yogrtdir=/path/to/libyogrt/spack/install/lib
gcc -o grt grt.c -L${yogrtdir} -Wl,-rpath,${yogrtdir} -lyogrt
./grt
2147483647

# try again with system install of libyogrt
yogrtdir=/usr/lib64
gcc -o grt grt.c -L${yogrtdir} -Wl,-rpath,${yogrtdir} -lyogrt
./grt 
3547
```

**Comment by robertkb** [comment]
Checking it out now

**Comment by adammoody** [comment]
Thanks @robertkb .  There may be several independent issues that are accumulating on this ticket.  We can work them each in turn and perhaps create separate issues if needed.

As a starting point, let's see if we can get the spack build of libyogrt to return correct values when called from within a SLURM allocation.  See my test case above that shows the incorrect behavior with spack and the correct behavior when using the system install on quartz.  We'll also want to check on LSF (lassen).

**Comment by adammoody** [comment]
I had also briefly looked at something like ``spack install libyogrt scheduler=slurm``, but that tries to install slurm via spack, which is not what we'd want.  If it turns out that going down that route is useful, we'd need to figure out how to register the system-installed slurm in the packages.yaml.

**Comment by adammoody** [comment]
I have to think someone at LLNL knows how to do these things, so we can ask around here if it's not obvious.  Do you have ideas, @gonsie?

**Comment by robertkb** [comment]
I have slurm in my packages.yaml.   
```
slurm:
    externals:
    - spec: slurm
      prefix: /usr
```
I don't remember if I added that myself, or got it from @gonsie when I copied her `packages.yaml`

Since it looks like libyogrt does not "automatically" select a scheduler, the spack line needs to specify it, and it seems like `spack install libyogrt scheduler=slurm` is the proper way to tell spack.

**Comment by adammoody** [comment]
@robertkb , in addition to getting spack builds of libyogrt for both SLURM and LSF working, let's also see if we can find the right package.yaml syntax needed to let someone register a system-installed libyogrt in case they have one.  Following your slurm entry above, maybe something like?
```
libyogrt:
    externals:
    - spec: libyogrt
      prefix: /usr
```

**Comment by robertkb** [comment]
@adammoody, that is exactly what I had for `libyogrt` in `packages.yaml` until this morning, when I commented it out, but looking through my old SCR spack build logs, I cannot verify whether or not it was getting included.

**Comment by robertkb** [comment]
The comments from @gonsie in the spack libyogrt `packages.py` log suggest that libyogrt detects the scheduler in some cases, but that appears not to be the case any more, at least not on quartz.

The way I'm leaning towards for fixing the spack build is to override the `install()` routine in packages.py, to call the standard spack `install()` method, then create a one-line `yogrt.conf` file containing the line `backend=XXX` where XXX is the value of `scheduler=XXX`. I'll work on that now, and see how it works on catalyst and lassen. If there's a nicer approach, let me know.

**Comment by adammoody** [comment]
That sounds good to me.

**Comment by robertkb** [comment]
I've put a pull request up on the spack repo: https://github.com/spack/spack/pull/19960

grt.c builds and runs correctly on quartz using:
```
spack install libyogrt scheduler=slurm
spack load libyogrt
salloc -N1 -ppdebug
gcc -o grt grt.c -lyogrt
./grt

```
I will try to post the PR to a libyogrt issue.

**Comment by adammoody** [comment]
That's great.

To save the Spack reviewers some time, it'd be nice to include LSF in this PR, too.  To test with LSF on Lassen, I think you can replace the ``salloc`` command with:

``bsub -nnodes 1 -q pdebug -W 60 -Is /bin/tcsh``

**Comment by robertkb** [comment]
I do plan to include LSF. I also have to fix some errors that their format checker found.￼ I will update it tomorrow.￼

**Comment by robertkb** [comment]
The following works on lassen:
```
spack install libyogrt scheduler=lsf
spack load libyogrt
xlc_r -o grt grt.c -lyogrt -llsf -lnsl -lrt
bsub -nnodes 1 -q pdebug -W 60 -Is /bin/bash
./grt
```
I don't know that we can get rid of the extra link libraries, but I'm not sure that we should expect spack to do that. Since the LSF API lib depends on -lnsl and -lrt, maybe those libraries need to be added to the libyogrt build config. I'll take a look at the libyogrt build and see if that's possible.

I'm going to clean up my spack changes and update the PR, then circle back and test catalyst and quartz again.

**Comment by robertkb** [comment]
I've updated my spack PR, but I'm still working on the library dependency issue. When I build libyogrt manually, the libyogrt-lsf.so file ends up including refs to liblsf, libnsl, and librt, so the -l flags are not required. When I build libyogrt with spack, I don't get the libraries in the libyogrt-lsf.so file, requiring them to be on the compile line. I have not yet tracked down the difference between the two build procedures, but I suspect that my interactive shell might be getting some env settings that spack does not see.

**Comment by robertkb** [comment]
I checked in the library fixes for LSF/lassen, so as soon as the automated check finish, I'll mark it ready for review.

**Comment by robertkb** [comment]
Marked ready for review

**Comment by adammoody** [comment]
Thanks, @robertkb .  I made a few comments on the libyogrt PR.

There are several subitems related to this current GitHub issue.  Trying to list them all in one place, I think we have:
1) update libyogrt spack to handle SLURM, and test that ``spack install libyogrt scheduler=slurm`` works
2) update libyogrt spack to handle LSF, and test that ``spack install libyogrt scheduler=lsf`` works
3) update the scr spack package to specify the proper libyogrt variant based on selected resource manager
4) identify the lines one needs to add to packages.yaml on SLURM so that a ``spack install scr`` uses the system installed libyogrt instead of installing libyogrt through spack, document those lines in our scr build docs
5) identify the lines one needs to add to packages.yaml on LSF so that a ``spack install scr`` uses the system installed libyogrt instead of installing libyogrt through spack, document those lines in our scr build docs
6) track down the cause and a fix for spack/spack#17894

With the libyogrt spack PR, I think we're in good shape for checking off items 1 and 2.

It sounds like you have a good start for 4 and 5 based on what you were already using, though maybe that needs tweaking to include the scheduler variant keyword?  I think we just need to test and write up those steps in the scr docs.

**Comment by adammoody** [comment]
@kathrynmohror , for another TODO list item, we should also add a gitlab test for libyogrt.  Something like:

1) submit a job with a 5 minute time limit
2) check that a call to libyogrt returns a remaining time value that is 5 minutes or less
3) wait ~30 seconds, call libyogrt again and check that time remaining has decreased by something close to 30 seconds

We'd want tests for both SLURM and LSF.

**Comment by robertkb** [comment]
@adammoody I saw your comments in the PR, and will get them tested and committed.

**Comment by adammoody** [comment]
Of the list above, I think items 1-5 are all just about done now.  Let's plan to close out this particular issue once those are done, and we'll move item 6 that deals with the ``libyogrt+static`` problem to a separate issue.

**Comment by adammoody** [comment]
@robertkb , I was wondering whether we could close out this issue.

From the list of 1-6 a couple comments up in this thread, I know we have items 1-3 resolved.  Item 6 has been moved out to its own issue.

Where do we stand on items 4-5?

Do you have that written up in your documentation branch?  If so, we should be good to close this issue.

**Comment by adammoody** [comment]
Thank you for all of your work on this, @robertkb !  By that time we accounted for all of the various cases, that was a hefty issue.
