### ISSUE TITLE
Update scr spack to use /dev/shm instead of /tmp

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#255]
The develop branch made the switch from /tmp (which is sometimes tmpfs and sometimes not) to /dev/shm (which is almost always tmpfs).

https://github.com/LLNL/scr/commit/fa2e6546e644e22521b4e2d96cdfb71398793c21

At some point, we'll want to change our spack package to also use /dev/shm:

https://github.com/spack/spack/blob/f7e3ef1b5c92bc9d74f559a79aee2e38405c56b0/var/spack/repos/builtin/packages/scr/package.py#L84

**Comment by adammoody** [comment]
@robertkb pointed out that mac's do not have a /dev/shm, so this path is not universal across systems.

**Comment by robertkb** [comment]
Every system on the June Top500 is Linux-based. No oddball outliers left there.

**Comment by adammoody** [comment]
Some relevant articles:
https://superuser.com/questions/45342/when-should-i-use-dev-shm-and-when-should-i-use-tmp
https://superuser.com/questions/448585/is-there-an-implementation-of-tmpfs-for-mac-os-x

Maybe we could check for /dev/shm in cmake and auto fallback to /tmp or throw an error and helpful error message if not found?

**Comment by adammoody** [comment]
I see there are commands to list the current OS and platform, like:
```
spack arch --operating-system
spack arch --platform
```
Happening to run those on my mac, I get:
```
spack.git/bin/spack arch --operating-system
mojave

spack.git/bin/spack arch --platform
darwin
```
We could key off of those as “spec.platform” or “spec.os”, though I imagine keeping the list up-to-date with Apple releases could be problematic.

If we can't handle this automatically for users, it'd be nice to at least throw an error during mac builds.  Then we could document the variant options that mac users need to set as a work around.

**Comment by adammoody** [comment]
To be fixed with https://github.com/spack/spack/pull/22073
