### ISSUE TITLE
Echo selected options in cmake output

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#297]
Let's update ``CMakeLists.txt`` to echo all configurable selections, like the resource manager, async option, and file locking, etc.  This will help people identify incorrect settings.

For example, someone might realize there is a configuration problem if they see the following cmake output while building SCR for an ``LSF`` system:
```
cmake ..
-- SCR_RESOURCE_MANAGER: SLURM
```

**Comment by gonsie** [comment]
I think we need to print them each individually.

**Comment by adammoody** [comment]
Thanks, @gonsie .
