### ISSUE TITLE
Verify Quick Start with CMake

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#301]
Following the CMake path on the Quick Start page from start to finish as a new user would, verify that all steps work as described.  Fix problems where needed.

https://github.com/LLNL/scr/blob/develop/doc/rst/users/quick.rst

Resolve TODO items for CMake at:
- https://github.com/LLNL/scr/blob/develop/doc/rst/users/quick.rst#building-the-scr-test_api-example
- https://github.com/LLNL/scr/blob/develop/doc/rst/users/quick.rst#running-the-scr-test_api-example

**Comment by adammoody** [comment]
We might still have a mismatch on the CMake instructions for building test_api.

https://github.com/LLNL/scr/blob/develop/doc/rst/users/quick.rst#building-the-scr-test_api-example

If I follow the steps as we have them written, I get the following error:
```
>>: cd ../install/share/scr/examples
/path/to/scr/install/share/scr/examples

>>: make test_api
mpicc -g -O3 -g -O0 -I/path/to/scr/install/include -c -o test_common.o test_common.c
mpicc -g -O3 -g -O0 -I/path/to/scr/install/include -o test_api test_common.o test_api.c \
   -L/path/to/scr/install/lib64 -Wl,-rpath,/path/to/scr/install/lib64 -lscr
/usr/bin/ld: warning: libdtcmp.so, needed by /path/to/scr/install/lib64/libscr.so, not found (try using -rpath or -rpath-link)
/path/to/scr/install/lib64/libscr.so: undefined reference to `DTCMP_Init'
/path/to/scr/install/lib64/libscr.so: undefined reference to `DTCMP_Finalize'
/path/to/scr/install/lib64/libscr.so: undefined reference to `DTCMP_Rankv_strings'
make: *** [test_api] Error 1
```
To resolve this for the CMake path, we could change the instructions to direct people to compile test_api in the CMake build directory instead.  The other fix would be to update the ``makefile`` that gets installed in ``install/share/scr/examples``.

**Comment by adammoody** [comment]
It would be nice to fix the makefile, since it's kind of broken in the general case.  That will also solve the request in https://github.com/LLNL/scr/issues/294

However, for 3.0rc1, I think we should just change our Quick Start instructions to ask people who are following the CMake path to build test_api from the CMake build directory rather than from the ``<install>/share/scr/examples`` directory.

Our existing instructions for building in ``<install>/share/scr/examples`` may actually be correct for someone following the Spack path, but I haven't tried it yet.

**Comment by gonsie** [comment]
The install step of SCR was breaking the libscr rpaths for linux. Everything should work now.
