### ISSUE TITLE
Verify Compile and Link flags for CMake install of SCR

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#303]
For a CMake install of SCR, verify that the compile and link flags for an application are listed correctly here:

https://github.com/LLNL/scr/blob/develop/doc/rst/users/integration.rst#building-with-the-scr-library

We need to verify both a dynamic link and a static link of libscr.

**Comment by gonsie** [comment]
The link flags in the documentation point to `lib64` ... but that value is platform specific. We are using the CMake package [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) which should select either `lib` or `lib64` as appropriate for the platform.

On my mac the location is `lib`; while on platforms such as quartz the value is `lib64`.

I'll make a note on the documentation page, but I'll leave it as `lib64` in the documentation.
