### ISSUE TITLE
SCR Spack package specifying wrong CMake parameter for system config file

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#310]
While testing the system config file from a spack install, I found that the path is still defaulting to ``/etc/scr/scr.conf``.

I think this is because our spack package is setting ``CMAKE_SCR_CONFIG_FILE`` instead of ``SCR_CONFIG_FILE``:
https://github.com/spack/spack/blob/c011e2156fad1e632fa90702d89fe41b110fe42a/var/spack/repos/builtin/packages/scr/package.py#L121

**Comment by adammoody** [comment]
@CamStan , when you update the SCR spack package, would you please also include a fix for this?

**Comment by CamStan** [comment]
Nice catch. Yup, I'll update that.

**Comment by CamStan** [comment]
Addressed in https://github.com/spack/spack/pull/23378
