### ISSUE TITLE
print internal config values during SCR_Init when SCR_DEBUG is set

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#341]
We want to print the actual values that SCR is using.  We'll start by just worrying about params within the library (not the scripts).

This will account for most of the params defined here:
https://scr.readthedocs.io/en/latest/users/config.html#scr-parameters 

To be sane, we could print these when they are set.  SCR sets most of its params in this function:
https://github.com/LLNL/scr/blob/33d11acdb557f1578aa1210acfd1c9ac363c1d7d/src/scr.c#L563 

Many of them are set in a pattern of the following form, which looks for a runtime setting, and falls back to a compile time setting if nothing is set.
https://github.com/LLNL/scr/blob/33d11acdb557f1578aa1210acfd1c9ac363c1d7d/src/scr.c#L710-L715

We'll want to just print on rank 0, and we could call ``scr_dbg`` to print the message, so maybe just add something like this to the above example:
```
if (scr_rank_world == 0) {
  scr_dbg(1, "SCR_CNTL_BASE=%s", scr_cntl_base);
}
```

In addition, we'll want to print the active store and redundancy descriptors that SCR has created.  For that, we could probably just call ``kvtree_print`` to print the ``scr_storedesc_hash`` and ``scr_reddesc_hash`` hashes that are defined within the ``scr_get_params`` function.

We may find that we also want to print info from calls like ``scr_storedescs_create()`` and ``scr_reddescs_create()``.  Let's start with the hashes and see how far that gets us.

**Comment by adammoody** [comment]
Related to https://github.com/LLNL/scr/issues/256

**Comment by hbchen1984** [comment]
06142021: Submit updated scr.c code for supporting the new print format (SCR parameters)
     scr_dbg(1, "SCR_ENABLE=0");
     scr_dbg(1, "SCR_ENABLE=1");
     scr_dbg(1, "SCR_DEBUG=%d",scr_debug);
     scr_dbg(1, "SCR_PREFIX=%s", scr_prefix);
     scr_dbg(1, "SCR_LOG_ENABLE=%d", scr_log_enable);
     scr_dbg(1, "SCR_LOG_TXT_ENABLE=%d", scr_log_txt_enable);
     scr_dbg(1, "SCR_LOG_SYSLOG_ENABLE=%d", scr_log_syslog_enable);
     scr_dbg(1, "SCR_LOG_DB_EBABLE=%d", scr_log_db_enable);
     scr_dbg(1, "SCR_LOG_DB_DEBUG=%d", scr_log_db_debug);
     scr_dbg(1, "SCR_LOG_DB_HOST=%s", scr_log_db_host);
     scr_dbg(1, "SCR_LOG_DB_USER=%s", scr_log_db_user);
     scr_dbg(1, "SCR_LOG_DB_PASS=%s", scr_log_db_pass);
     scr_dbg(1, "SCR_LOG_DB_NAME=%s", scr_log_db_name);
     scr_dbg(1, "SCR_USER_NAME=%s", scr_username);
     scr_dbg(1, "SCR_JOB_ID=%s", scr_jobid);
     scr_dbg(1, "SCR_JOB_NAME=%s", scr_jobname);
     scr_dbg(1, "SCR_CLUSTER_NAME=%s", scr_clustername);
     scr_dbg(1, "SCR_CNTL_BASE=%s", scr_cntl_base);
     scr_dbg(1, "SCR_CACHE_BASE=%s", scr_cache_base);
     scr_dbg(1, "SCR_CACHE_SIZE=%d", scr_cache_size);
     scr_dbg(1, "SCR_COPY_TYPE=SCR_COPY_SINGLE");
     scr_dbg(1, "SCR_COPY_TYPE=SCR_COPY_PARTNER");
     scr_dbg(1, "SCR_COPY_TYPE=SCR_COPY_XOR");
     scr_dbg(1, "SCR_COPY_TYPE=SCR_COPY_RS");
     scr_dbg(1, "SCR_COPY_TYPE=SCR_COPY_FILE");
     scr_dbg(1, "SCR_COPY_TYPE=%d", scr_copy_type);
     scr_dbg(1, "SCR_SET_SIZE=%d", scr_set_size);
     scr_dbg(1, "SCR_SET_FAILURES=%d", scr_set_failures);
     scr_dbg(1, "SCR_GROUPO=%s", scr_group);
     scr_dbg(1, "SCR_CACHE_BYPASS=%d", scr_cache_bypass);
     scr_dbg(1, "SCR_HALTS_SECONDS=%d", scr_halt_seconds);
     scr_dbg(1, "SCR_HALT_EXITS=%d", scr_halt_exit);
     scr_dbg(1, "SCR_MPI_BUF_SIZE=%d", scr_mpi_buf_size);
     scr_dbg(1, "SCR_CACHE_PURGE=%d", scr_purge);
     scr_dbg(1, "SCR_DISTRIBUTE=%d", scr_distribute);
     scr_dbg(1, "SCR_FETCH=%d", scr_fetch);
     scr_dbg(1, "SCR_FETCH_WIDTH=%d", scr_fetch_width);
     scr_dbg(1, "SCR_CURRENT=%s", scr_fetch_current);
     scr_dbg(1, "SCR_FLUSH=%d", scr_flush);
     scr_dbg(1, "SCR_FLUSH_WIDTH=%d", scr_flush_width);
     scr_dbg(1, "SCR_FLUSH_TYPE=%s", scr_flush_type);
     scr_dbg(1, "SCR_FLUSH_ON_RESTART=%d", scr_flush_on_restart);
     scr_dbg(1, "SCR_GLOBAL_RESTART=%d", scr_global_restart);
     scr_dbg(1, "SCR_DROP_AFTER_CURRENT=%d", scr_drop_after_current);
     scr_dbg(1, "SCR_PREFIX_SIZE=%d", scr_prefix_size);
     scr_dbg(1, "SCR_PREFIX_PURGE=%d ", scr_prefix_purge);
     scr_dbg(1, "SCR_FLUSH_ASYNC=%d", scr_flush_async);
     scr_dbg(1, "SCR_FLUSH_ASYNC_BW=%f", scr_flush_async_bw);
     scr_dbg(1, "SCR_FLUSH_ASYNC_PERCEN=%f", scr_flush_async_percent);
     scr_dbg(1, "SCR_FILE_BUF_SIZE=%d", scr_file_buf_size);
     scr_dbg(1, "SCR_COPY_METADATA=%d", scr_copy_metadata);
     scr_dbg(1, "SCR_AXL_MKDIR=%d", scr_axl_mkdir);
     scr_dbg(1, "SCR_CRC_ON_COPY=%d", scr_crc_on_copy);
     scr_dbg(1, "SCR_CRC_ON_FLUSH=%d", scr_crc_on_flush);
     scr_dbg(1, "SCR_CRC_ON_DELETE=%d" , scr_crc_on_delete);
     scr_dbg(1, "SCR_CHECKPOINT_INTERVAL=%d", scr_checkpoint_interval);
     scr_dbg(1, "SCR_HECKPOINT_SECONDS=%d", scr_checkpoint_seconds); 
     scr_dbg(1, "SCR_CHECKPOINT_OVERHEAD=%f", scr_checkpoint_overhead);

Testing log : On Lassen 
[chen126@lassen1:examples]$ cat   06142021-lassen-test-log-T341 
[1] SCR_DEBUG is disabled

[chen126@lassen33:examples]$ jsrun -r 1 ./test_api 
Warning: Overriding spectrum-mpi/rolling-release (module loaded must exactly match)
Warning: Using      spectrum-mpi/2020.08.19 to match app's MPI
Please tell John Gyllenhaal (gyllen@llnl.gov, 4-5485) if this MPI env fix doesn't work
      STORE
        /dev/shm
          COUNT = 1
      CKPT
        0
          SET_SIZE = 8
          GROUP = NODE
          TYPE = XOR
          STORE = /dev/shm
Init: Min 0.039853 s	Max 0.039853 s	Avg 0.039853 s
At least one rank (perhaps all) did not find its checkpoint
Completed checkpoint 1.
Completed checkpoint 2.
Completed checkpoint 3.
Completed checkpoint 4.
Completed checkpoint 5.
Completed checkpoint 6.
FileIO: Min    0.28 MB/s	Max    0.28 MB/s	Avg    0.28 MB/s	Agg    1.14 MB/s

[2] SCR_DEBUG is enabled 
[chen126@lassen33:examples]$ export SCR_DEBUG=1 
[chen126@lassen33:examples]$ jsrun -r 1 ./test_api 
Warning: Overriding spectrum-mpi/rolling-release (module loaded must exactly match)
Warning: Using      spectrum-mpi/2020.08.19 to match app's MPI
Please tell John Gyllenhaal (gyllen@llnl.gov, 4-5485) if this MPI env fix doesn't work
SCR v3.0.0: rank 0 on lassen30: SCR_DEBUG=1
SCR v3.0.0: rank 0 on lassen30: SCR_PREFIX=/p/gpfs1/chen126/scr32b/scr/build/examples
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_ENABLE=0
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_TXT_ENABLE=1
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_SYSLOG_ENABLE=1
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_DB_EBABLE=0
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_DB_DEBUG=0
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_DB_HOST=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_DB_USER=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_DB_PASS=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_LOG_DB_NAME=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_USER_NAME=chen126
SCR v3.0.0: rank 0 on lassen30: SCR_JOB_ID=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_JOB_NAME=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_CLUSTER_NAME=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_CNTL_BASE=/dev/shm
SCR v3.0.0: rank 0 on lassen30: SCR_CACHE_BASE=/dev/shm
SCR v3.0.0: rank 0 on lassen30: SCR_CACHE_SIZE=1
SCR v3.0.0: rank 0 on lassen30: SCR_COPY_TYPE=4
SCR v3.0.0: rank 0 on lassen30: SCR_SET_SIZE=8
SCR v3.0.0: rank 0 on lassen30: SCR_SET_FAILURES=2
SCR v3.0.0: rank 0 on lassen30: SCR_GROUPO=NODE
SCR v3.0.0: rank 0 on lassen30: SCR_CACHE_BYPASS=1
SCR v3.0.0: rank 0 on lassen30: SCR_HALTS_SECONDS=0
SCR v3.0.0: rank 0 on lassen30: SCR_HALT_EXITS=0
SCR v3.0.0: rank 0 on lassen30: SCR_MPI_BUF_SIZE=131072
SCR v3.0.0: rank 0 on lassen30: SCR_CACHE_PURGE=0
SCR v3.0.0: rank 0 on lassen30: SCR_DISTRIBUTE=1
SCR v3.0.0: rank 0 on lassen30: SCR_FETCH=1
SCR v3.0.0: rank 0 on lassen30: SCR_FETCH_WIDTH=256
SCR v3.0.0: rank 0 on lassen30: SCR_CURRENT=(null)
SCR v3.0.0: rank 0 on lassen30: SCR_FLUSH=10
SCR v3.0.0: rank 0 on lassen30: SCR_FLUSH_WIDTH=256
SCR v3.0.0: rank 0 on lassen30: SCR_FLUSH_TYPE=SYNC
SCR v3.0.0: rank 0 on lassen30: SCR_FLUSH_ON_RESTART=0
SCR v3.0.0: rank 0 on lassen30: SCR_GLOBAL_RESTART=0
SCR v3.0.0: rank 0 on lassen30: SCR_DROP_AFTER_CURRENT=0
SCR v3.0.0: rank 0 on lassen30: SCR_PREFIX_SIZE=0
SCR v3.0.0: rank 0 on lassen30: SCR_PREFIX_PURGE=0 
SCR v3.0.0: rank 0 on lassen30: SCR_FLUSH_ASYNC=0
SCR v3.0.0: rank 0 on lassen30: SCR_FLUSH_ASYNC_BW=209715200.000000
SCR v3.0.0: rank 0 on lassen30: SCR_FLUSH_ASYNC_PERCEN=0.000000
SCR v3.0.0: rank 0 on lassen30: SCR_FILE_BUF_SIZE=1048576
SCR v3.0.0: rank 0 on lassen30: SCR_COPY_METADATA=1
SCR v3.0.0: rank 0 on lassen30: SCR_AXL_MKDIR=0
SCR v3.0.0: rank 0 on lassen30: SCR_CRC_ON_COPY=0
SCR v3.0.0: rank 0 on lassen30: SCR_CRC_ON_FLUSH=1
SCR v3.0.0: rank 0 on lassen30: SCR_CRC_ON_DELETE=0
SCR v3.0.0: rank 0 on lassen30: SCR_CHECKPOINT_INTERVAL=0
SCR v3.0.0: rank 0 on lassen30: SCR_HECKPOINT_SECONDS=0
SCR v3.0.0: rank 0 on lassen30: SCR_CHECKPOINT_OVERHEAD=0.000000
      STORE
        /dev/shm
          COUNT = 1
      CKPT
        0
          SET_SIZE = 8
          GROUP = NODE
          TYPE = XOR
          STORE = /dev/shm

SCR v3.0.0: rank 0 on lassen30: Attempting to distribute and rebuild dataset 6
SCR v3.0.0: rank 0 on lassen30: Rebuilt dataset 6
SCR v3.0.0: rank 0 on lassen30: Scalable restart succeeded for checkpoint 6, took 0.005559 secs
Init: Min 0.019089 s	Max 0.019091 s	Avg 0.019090 s
Restarting from checkpoint named ckpt.6
SCR v3.0.0: rank 0 on lassen30: Deleting dataset 6 `ckpt.6' from cache
SCR v3.0.0: rank 0 on lassen30: Starting dataset 7 `ckpt.7'
SCR v3.0.0: rank 0 on lassen30: scr_complete_output: 1.343483 secs, 2.097186e+06 bytes, 1.488692 MB/s, 0.372173 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: Initiating flush of dataset 7 `ckpt.7'
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: 0.019854 secs, 2.097186e+06 bytes, 100.737022 MB/s, 25.184255 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: Flush succeeded for dataset 7 `ckpt.7'
Completed checkpoint 7.
SCR v3.0.0: rank 0 on lassen30: Deleting dataset 7 `ckpt.7' from cache
SCR v3.0.0: rank 0 on lassen30: Starting dataset 8 `ckpt.8'
SCR v3.0.0: rank 0 on lassen30: scr_complete_output: 1.346103 secs, 2.097186e+06 bytes, 1.485794 MB/s, 0.371449 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: Initiating flush of dataset 8 `ckpt.8'
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: 0.022540 secs, 2.097186e+06 bytes, 88.732871 MB/s, 22.183218 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: Flush succeeded for dataset 8 `ckpt.8'
Completed checkpoint 8.
SCR v3.0.0: rank 0 on lassen30: Deleting dataset 8 `ckpt.8' from cache
SCR v3.0.0: rank 0 on lassen30: Starting dataset 9 `ckpt.9'
SCR v3.0.0: rank 0 on lassen30: scr_complete_output: 1.325007 secs, 2.097186e+06 bytes, 1.509451 MB/s, 0.377363 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: Initiating flush of dataset 9 `ckpt.9'
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: 0.041016 secs, 2.097186e+06 bytes, 48.762487 MB/s, 12.190622 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: Flush succeeded for dataset 9 `ckpt.9'
Completed checkpoint 9.
SCR v3.0.0: rank 0 on lassen30: Deleting dataset 9 `ckpt.9' from cache
SCR v3.0.0: rank 0 on lassen30: Starting dataset 10 `ckpt.10'
SCR v3.0.0: rank 0 on lassen30: scr_complete_output: 1.356726 secs, 2.097186e+06 bytes, 1.474161 MB/s, 0.368540 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: Initiating flush of dataset 10 `ckpt.10'
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: 0.015068 secs, 2.097186e+06 bytes, 132.736394 MB/s, 33.184098 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: Flush succeeded for dataset 10 `ckpt.10'
Completed checkpoint 10.
SCR v3.0.0: rank 0 on lassen30: Deleting dataset 10 `ckpt.10' from cache
SCR v3.0.0: rank 0 on lassen30: Starting dataset 11 `ckpt.11'
SCR v3.0.0: rank 0 on lassen30: scr_complete_output: 1.363911 secs, 2.097186e+06 bytes, 1.466395 MB/s, 0.366599 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: Initiating flush of dataset 11 `ckpt.11'
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: 0.015629 secs, 2.097186e+06 bytes, 127.967784 MB/s, 31.991946 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: Flush succeeded for dataset 11 `ckpt.11'
Completed checkpoint 11.
SCR v3.0.0: rank 0 on lassen30: Deleting dataset 11 `ckpt.11' from cache
SCR v3.0.0: rank 0 on lassen30: Starting dataset 12 `ckpt.12'
SCR v3.0.0: rank 0 on lassen30: scr_complete_output: 1.368924 secs, 2.097186e+06 bytes, 1.461025 MB/s, 0.365256 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: Initiating flush of dataset 12 `ckpt.12'
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: 0.021944 secs, 2.097186e+06 bytes, 91.144549 MB/s, 22.786137 MB/s per proc
SCR v3.0.0: rank 0 on lassen30: scr_flush_sync: Flush succeeded for dataset 12 `ckpt.12'
Completed checkpoint 12.
FileIO: Min    0.29 MB/s	Max    0.29 MB/s	Avg    0.29 MB/s	Agg    1.16 MB/s

ckpt.1:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.10:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.11:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.12:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.2:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.3:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.4:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.5:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.6:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.7:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.8:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt

ckpt.9:
rank_0.ckpt
rank_1.ckpt
rank_2.ckpt
rank_3.ckpt


.scr:
total 14K
-rw-r--r-- 1 chen126 chen126    0 Jun 14 08:01 app.conf
-rw-r--r-- 1 chen126 chen126  353 Jun 14 08:01 flush.scr
-rw-r--r-- 1 chen126 chen126   67 Jun 14 08:01 halt.scr
-rw-r--r-- 1 chen126 chen126 3.9K Jun 14 08:01 index.scr
-rw-r--r-- 1 chen126 chen126   44 Jun 14 08:01 nodes.scr
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.1
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.10
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.11
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.12
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.2
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.3
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.4
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.5
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.6
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.7
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.8
drwxr-xr-x 2 chen126 chen126 4.0K Jun 14 08:01 scr.dataset.9

.scr/scr.dataset.1:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.10:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 225 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 300 Jun 14 08:01 summary.scr

.scr/scr.dataset.11:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 225 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 300 Jun 14 08:01 summary.scr

.scr/scr.dataset.12:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 225 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 300 Jun 14 08:01 summary.scr

.scr/scr.dataset.2:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.3:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.4:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.5:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.6:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.7:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.8:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

.scr/scr.dataset.9:
total 1.5K
-rw-r--r-- 1 chen126 chen126 110 Jun 14 08:01 rank2file
-rw-r--r-- 1 chen126 chen126 221 Jun 14 08:01 rank2file.0.0
-rw-r--r-- 1 chen126 chen126 297 Jun 14 08:01 summary.scr

**Comment by adammoody** [comment]
Added with https://github.com/LLNL/scr/pull/363
