### ISSUE TITLE
"restart" test in make test fails with an MPI_Abort on LSF

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#342]
When running the "make test" in a four-node allocation on LSF, the "restart" portion of the test throws an MPI_Abort, with a message like:
```
OPAL ERROR: Unreachable in file ext3x_client.c at line 112
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort.
```
One can also see this scattered in the output by running ``ctest --verbose``.

Our test script in this case tries to run ``./test_api`` twice.
https://github.com/LLNL/scr/blob/33d11acdb557f1578aa1210acfd1c9ac363c1d7d/examples/run_test.sh#L15-L21

We then ``jsrun`` the ``run_test.sh`` script.
https://github.com/LLNL/scr/blob/33d11acdb557f1578aa1210acfd1c9ac363c1d7d/cmake/SCR_ADD_TEST.cmake#L16

So we end up with something like:
```
jsrun --nrs 1 -r 1 run_test.sh ./test_api restart
```

I think the error is showing up because this means we end up calling ``MPI_Init`` twice, once for the original run, and then a second time for the "restart" run all within a single ``jsrun`` job launch.  Apparently IBM MPI / LSF do not support this mode of operation.  It will likely fail for other MPI / job launcher combinations.

As a fix, we could perhaps move the ``jsrun`` inside of the ``run_test.sh`` script, so that each ``./test_api`` gets its own ``jsrun``.  I think we instead need something like:
```
# run the script without a launch
run_test.sh ./test_api restart
```
And then inside of run_test.sh:
```
# run each MPI job with its own jsrun
jsrun --nrs 1 -r 1 ./test_api
```

Going this route would also require some changes to the cleanup step.  There are likely other/better ways to solve it.

As a bonus item, we are not catching the fact that the restarted job actually fails.  All tests report success even though the restart job has actually failed.

**Comment by adammoody** [comment]
@gonsie , is this something you'd have time to help with before the v3.0rc2 release at the end of the month?

**Comment by gonsie** [comment]
Was this working before your change in b1cc5ea7c871a753953a5573a08fff19ec8641b0?

**Comment by adammoody** [comment]
My guess is that they would have been failing in the same way before that commit, but I didn't check.  The tests were all reporting as passed before and after that change, but they could have been failing in the same way.

**Comment by adammoody** [comment]
Just pushed a fix to detect and report the fact that restart jobs are failing.

https://github.com/LLNL/scr/commit/cbe3a4626f3ac4d7cd919414196da8cdc43d9bbf 

We'll still need to fix the run_test.sh to resolve the problem.

**Comment by adammoody** [comment]
I think this is now fixed https://github.com/LLNL/scr/pull/349

**Comment by adammoody** [comment]
@robertkb , let me know if this managed to break your test setup.
