### ISSUE TITLE
Test at scale with 200+ nodes

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#344]
- Run SCR test_api at scale to check performance and functionality
- Check redundancy schemes, including new RS
- Include scavenge and rebuild tests
- Check sync and async flush methods
- Do this on both LSF and SLURM

**Comment by adammoody** [comment]
When testing the parallel file system, let's run two tests.
1) Measure the cost to write to the parallel file system without using SCR
```
# test_api skips SCR calls and writes its files direct
# to the parallel file system when using the --path call
test_api --path /p/gpfs1/${USER}/...
```
2) Measure the cost when using SCR bypass mode
```
# use SCR in test_api, but configure SCR for bypass mode
SCR_CACHE_BYPASS=1
test_api
```
The goal here is to check that bypass does not add substantial overhead as when not using SCR at all.  Using SCR will add some overhead as SCR maintains the index file and other metadata, which impose some extra ``fsync`` calls.  Hopefully, we can keep this overhead low.

**Comment by gonsie** [comment]
is the scaling study that @hbchen1984 is working on cover this?

**Comment by adammoody** [comment]
Yes, @hbchen1984 's tests are working to cover these.

**Comment by gonsie** [comment]
great, closing this issue as the performance study will most likely be ongoing and is tracked elsewhere.
