### ISSUE TITLE
support global storage as cache locations

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#351]
While it should be possible to use global storage as a cache level, we currently have some hard-coded assumptions and scalability issues because SCR generally assumes cache locations are using node-local storage.

For example, when inspecting the cache on restart, one rank is responsible for distributing work.  With global storage, this means rank 0 will have to talk with every process in the job, which becomes an N-to-1 bottleneck.

We should extend SCR to efficiently support global cache locations.

Related to https://github.com/LLNL/scr/issues/133

**Comment by adammoody** [comment]
Replaced with more specific issues:
https://github.com/LLNL/scr/issues/489
https://github.com/LLNL/scr/issues/493
https://github.com/LLNL/scr/issues/494

**Comment by mShining** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
