### ISSUE TITLE
Support parsing environment variables in config files

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#38]
Many sites define job-specific directories that users may write to, which are define via strings like: /scratch/$USER/$SLURM_JOBID.  To enable different sites to configure SCR, we need to provide a way for users to build dynamic directory paths like this for their cache and control directories.

**Comment by adammoody** [comment]
@becker33, the new code may already resolve this issue.  Can you run some smoke tests with the library and the scripts to verify it's working as expected?  In particular, try setting a cache location to something like /dev/shm/$SLURM_JOBID and see if things work.  Given that the code is there, it'd be nice to claim this support with the next release.

**Comment by becker33** [comment]
Since we apparently already did this, I'm closing it as resolved.
