### ISSUE TITLE
SCR_Config does no allow '=' character in configuration values

### ISSUE THREAD

**Issue by mcfadden8** [LLNL/scr#432]
The parser in SCR_Config treats '=' as an invalid character within a value for a given token.  This causes calling applications to fail when they pass in directory path names that contained an '=' character.

This failure behavior is inconsistent because when the application uses environment variables instead of SCR_Config, this particular character is allowed.

**Comment by adammoody** [comment]
Nice catch, @mcfadden8 .

I suppose we might also have trouble with any path names containing spaces.  Accounting for spaces is probably a harder fix, but it's good to note in case that comes up.  Perhaps we could include a note in the ``SCR_Config`` documentation to state that we don't yet support values with embedded space characters.

**Comment by adammoody** [comment]
Resolved with https://github.com/LLNL/scr/pull/433

Thanks for finding and fixing, @mcfadden8
