### ISSUE TITLE
tests: enable CI or step in release process to run manually

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#445]
Now that we have some tests for SCR and the components, we should enable them for CI or at least document steps on how to run all tests before stamping a new release.

**Comment by adammoody** [comment]
@CamStan , we can use this issue for discussion on the CI tests.

Since tests cannot be fully automated with each commit yet, let's create a confluence page that describes:
- where one goes to see the output history of the tests
- how one kicks off the tests manually
- how one pushes newly committed code from GitHub into gitlab and then executes the tests against the new code
 
Let's also add a step in our release process documentation to verify the tests before a stamping a new release.  It's not necessary that all tests pass, but any failing tests should be well understood.  We should include a link to the above confluence page from the release guide.

**Comment by CamStan** [comment]
Sounds good! I'll get that page going.

**Comment by gonsie** [comment]
@CamStan did you start a new page somewhere? I think we should maybe just add an item in the component release template that says 'tests pass in gitlab CI'

**Comment by CamStan** [comment]
I have not started a new page. 😞  This one slipped through the cracks on me.

**Comment by gonsie** [comment]
no worries! I don't think a new page is needed. I will incorporate this into our existing how to package a release page. thanks!
