### ISSUE TITLE
Develop MPI-based scavenge

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#49]
Some systems don't support pdsh, but they all generally support running MPI jobs.  We can improve portability by having an MPI-based scavenge in addition to our pdsh-based version.

Also with MPI, we can:
1) identify the list of datasets we can flush
2) rebuild missing files
3) initiate transfers when using vendor-specific APIs

The tricky part is to be sure we have a way to avoid bad nodes when launching the MPI-based scavenge app.

**Comment by adammoody** [comment]
If a parallel version with MPI is too tricky, we can look to fall back to running serial copy jobs (like pdsh) but using srun/aprun/mpirun.

**Comment by becker33** [comment]
Closing this as fixed by #69. Rather than remove the pdsh dependency, we run in a pdsh mode that is more widely supported. @adammoody feel free to reopen if you don't like this solution for the long-term.

**Comment by adammoody** [comment]
I'm good with closing this now.  There may be value in using an MPI-based scavenge down the road in order to speed up rebuilds, but it would require significant work.  We'll open a new issue for that later if the need arises.
