### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#50]
We should add some better logging, either to sys-log or some user-defined log file. something like that. If we used sys-log, the information would get automatically sucked in to splunk on the LC system.

**Comment by adammoody** [comment]
Logging to sys-log would be good.

As another early option, it'd be nice to append log entries to a simple text file that lives in the $SCR_PREFIX/.scr directory.

As a follow on after that, one neat use would be to then read that file during SCR_Init and estimate the optimal checkpoint frequency for a user's job, considering the job's past failure rate and checkpoint cost to then feed into Need_checkpoint.
