### ISSUE TITLE
nnf-dm - Create cmake install for NNFDM client api

### ISSUE THREAD

**Issue by mcfadden8** [LLNL/scr#508]
A sample client library has been provided in source code form here: https://github.com/NearNodeFlash/nnf-dm/tree/master/daemons/compute/_client-c.  The library is written in `go` and the Makefile will produce a `client.a` library file.  An `install` target needs to be made for the `client.a` library so that it may be included by AXL.

**Comment by mcfadden8** [comment]
@adammoody  - FYI, for testing purposes, my plan is to temporarily include the client.a library and associeated header file in the AXL repo.  Please let me know if you would like for me to do this in a different way.

**Comment by adammoody** [comment]
@mcfadden8 , I don't know what all is in there, but my main concern would be whether we have any NDA info or problems due to incompatible software licenses.  If something like that is a concern, we could create a branch and use our internal git repos instead.

**Comment by mcfadden8** [comment]
Closing this for now.  We will assume that a library will be provided at a later date and time and that we will not be building it ourselves.
