### ISSUE TITLE
cannot run configure

### ISSUE THREAD

**Issue by gongotar** [LLNL/scr#51]
Hi,

when I run configure I get following:
`config.status: creating Makefile
config.status: error: cannot find input file: `src/Makefile.in'`

before this by running autogen.sh script I get following error:
`configure.ac:57: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.`

As a result I cannot make/make install the code

**Comment by becker33** [comment]
@gongotar Was this on the master branch or on version 1.1.8? 

We are in the process of deprecating our Autotools build in favor of CMake. If you want a version with full autotools support, I would suggest version 1.1.8, which is the most recent stable release.

**Comment by gongotar** [comment]
Thanks, yes I was trying to compile the master branch. Now with 1.1.8 it works although I had to replace all `include "mpi.h"` commands in src folder with `include "path/to/my/mpich/lib"`.

**Comment by adammoody** [comment]
We switched to CMake, so I'll assume this issue is moot now.  Let us know if you still have problems building with the new build system.
