### ISSUE TITLE
Failed to record jobid

### ISSUE THREAD

**Issue by gongotar** [LLNL/scr#52]
Hi,

I'm trying to run the example "test_api" using scr 1.1.8. After the successful installation of dependencies and scr now I cannot execute the example because no job id will be created and I get following error:
`SCR v1.1.8 ABORT: rank 0 on ubuntu: Failed to record jobid @ scr.c:329
application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=0
:
system msg for write_line failure : Bad file descriptor`

I have looked in the code of "test_api" and found out that this error is thrown when "scr_init" is called. I also get this error by running all other examples. I'm using mpich v 3.2 on ubuntu. Any idea what the problem could be?

**Comment by gonsie** [comment]
You'll need to set a job id. You can do this in your environment or SCR config file. Setting `SCR_JOB_ID=456` should work.

**Comment by gongotar** [comment]
Thanks for the answer, is there any documentations about such parameters of SCR (ie. SCR_JOB_ID)? because I have searched in scr [documentation](https://computation.llnl.gov/sites/default/files/public/scr_users_manual.pdf) and haven't found any thing about setting job id in the environment. Now after setting job id I get following error about loading username and jobname from environment and I found also nothing about such parameters in the documentation (or in google search).
`SCR v1.1.8 WARNING: rank 0 on ubuntu: Failed to record cluster name @ scr.c:354
SCR v1.1.8 WARNING: rank 0 on ubuntu: Forcing copy type to SINGLE in redundancy descriptor 0 @ scr_reddesc.c:546
SCR v1.1.8 ERROR: rank 0 on ubuntu: Failed to read username or jobname from environment, disabling logging @ scr.c:822
Init: Min 0.008965 s	Max 0.008965 s	Avg 0.008965 s
0: SCR_Route_file failed during restart attempt
At least one rank (perhaps all) did not find its checkpoint
`
Can you please tell me where can I get a full documentation?

**Comment by kathrynmohror** [comment]
Sorry for the confusion with those error and warning messages, but they are nothing to worry about. Basically, they are saying that you didn't have the cluster name or job name set in your environment so it wasn't going to enable logging. Also, there was not a previous checkpoint to start your run from, so it is starting from scratch. 

Our next version of SCR (ready very soon) removes those error messages. We are also working on improving the documentation for that release, so hopefully that will help. For now the user guide that you have and asking us questions are your best sources of information.
