### ISSUE TITLE
Update user guide to v1.2

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#53]

**Comment by kathrynmohror** [comment]
I made a branch in the manuals repository for v1.2.0. I'll keep my changes pushed so you can see where I am.

**Comment by gonsie** [comment]
the branch was merged. The final document is attached.
[SCRv1.2-User-Manual.pdf](https://github.com/LLNL/scr/files/1497277/SCRv1.2-User-Manual.pdf)
