### ISSUE TITLE
Support machines that have no cache space (data can only be written to file system)

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#54]
For systems that have no SSDs available for cache or sufficient free memory for ramdisk, let's write checkpoints directly to the file system.  Let's assume we can still write filemap info to ramdisk, though (it's very small).

Route_file will need to do mkdir() calls here, probably for each component below the prefix directory.

We'll need to track file names and write SCR metadata that we'd normally get after a flush.

We need fetch to be aware of this, too.

The scavenge script will probably have to be modified, too.

**Comment by becker33** [comment]
Should this really be marked 1.2? I thought this was on a later time-scale.

**Comment by adammoody** [comment]
It's not a hard requirement for v1.2.  I listed it as a stretch goal hoping I'd find the time tol fit this in.  It's looking more like v1.3 right now.
