### ISSUE TITLE
Update and test Fortran interface for v1.2 API

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#62]

**Comment by adammoody** [comment]
Started this work on fortran branch

**Comment by gonsie** [comment]
We need to make sure the fortran example is up to date as well (`test_ckpt_F`). It seems to be failing due to route file *not* being called between start/complete pairs.

**Comment by adammoody** [comment]
Not complete, but moved to PR:
https://github.com/LLNL/scr/pull/84

**Comment by adammoody** [comment]
I think this is working on the PR.  Anyone up for reviewing it?

**Comment by CamStan** [comment]
All tests on the fortran branch on Bamboo just passed. It tests a what a merge into master would do.

**Comment by adammoody** [comment]
Thanks for the review, guys.  Merged and closed with https://github.com/LLNL/scr/commit/5759df64b5956020f49e52cfe145a3fc65025b05
