### ISSUE TITLE
Refactor documentation

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#97]

**Comment by adammoody** [comment]
I RST-ified the user guide latex files yesterday so that we can move it to readthedocs.

**Comment by adammoody** [comment]
I pushed this to our internal SCR docs repo for now.

**Comment by adammoody** [comment]
Now here: https://github.com/LLNL/scr/pull/111

**Comment by gonsie** [comment]
Woohoo! The documenation is now live at [scr.readthedocs.io](http://SCR.rtfd.io).

Still left to do:
- [ ] check settings at RTD
- [ ] add triggers so the docs get automatically rebuilt
- [ ] easy way to get the pdf back into the repo? That way the latest is always installed
- [ ] update / add links to readme

**Comment by gonsie** [comment]
This is addressed by a fix to #115. There is no automated way to get the pdf back into the repo, but we can do that manually for now.
